<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dypns.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *阿里号码手机号码获取入参
 *
 * Generated from protobuf message <code>proto.AliGetMobileParam</code>
 */
class AliGetMobileParam extends \Google\Protobuf\Internal\Message
{
    /**
     *阿里号码认证SDK获取token
     *
     * Generated from protobuf field <code>string accessToken = 1;</code>
     */
    protected $accessToken = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $accessToken
     *          阿里号码认证SDK获取token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Dypns::initOnce();
        parent::__construct($data);
    }

    /**
     *阿里号码认证SDK获取token
     *
     * Generated from protobuf field <code>string accessToken = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->accessToken;
    }

    /**
     *阿里号码认证SDK获取token
     *
     * Generated from protobuf field <code>string accessToken = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessToken = $var;

        return $this;
    }

}

