<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pay.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.AliPayReturn</code>
 */
class AliPayReturn extends \Google\Protobuf\Internal\Message
{
    /**
     *支付宝APP支付返回参数（支付宝）
     *
     * Generated from protobuf field <code>optional string payParam = 1;</code>
     */
    protected $payParam = null;
    /**
     *wap返回参数
     *
     * Generated from protobuf field <code>optional string h5Url = 2;</code>
     */
    protected $h5Url = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payParam
     *          支付宝APP支付返回参数（支付宝）
     *     @type string $h5Url
     *          wap返回参数
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     *支付宝APP支付返回参数（支付宝）
     *
     * Generated from protobuf field <code>optional string payParam = 1;</code>
     * @return string
     */
    public function getPayParam()
    {
        return isset($this->payParam) ? $this->payParam : '';
    }

    public function hasPayParam()
    {
        return isset($this->payParam);
    }

    public function clearPayParam()
    {
        unset($this->payParam);
    }

    /**
     *支付宝APP支付返回参数（支付宝）
     *
     * Generated from protobuf field <code>optional string payParam = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPayParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->payParam = $var;

        return $this;
    }

    /**
     *wap返回参数
     *
     * Generated from protobuf field <code>optional string h5Url = 2;</code>
     * @return string
     */
    public function getH5Url()
    {
        return isset($this->h5Url) ? $this->h5Url : '';
    }

    public function hasH5Url()
    {
        return isset($this->h5Url);
    }

    public function clearH5Url()
    {
        unset($this->h5Url);
    }

    /**
     *wap返回参数
     *
     * Generated from protobuf field <code>optional string h5Url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setH5Url($var)
    {
        GPBUtil::checkString($var, True);
        $this->h5Url = $var;

        return $this;
    }

}

