<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/alipush.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *推送返回结果
 *
 * Generated from protobuf message <code>proto.AliPushResponse</code>
 */
class AliPushResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *消息ID
     *
     * Generated from protobuf field <code>string messageId = 1;</code>
     */
    protected $messageId = '';
    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 2;</code>
     */
    protected $requestId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $messageId
     *          消息ID
     *     @type string $requestId
     *          请求ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Alipush::initOnce();
        parent::__construct($data);
    }

    /**
     *消息ID
     *
     * Generated from protobuf field <code>string messageId = 1;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->messageId;
    }

    /**
     *消息ID
     *
     * Generated from protobuf field <code>string messageId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->messageId = $var;

        return $this;
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 2;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->requestId;
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestId = $var;

        return $this;
    }

}

