<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/amap.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *AmapLocationParam 高德（起始,结束）经纬度参数
 *
 * Generated from protobuf message <code>proto.AmapLocationParam</code>
 */
class AmapLocationParam extends \Google\Protobuf\Internal\Message
{
    /**
     *出发点经纬度（只有距离测量时支持|号分隔多个）
     *
     * Generated from protobuf field <code>string origin = 1;</code>
     */
    protected $origin = '';
    /**
     *目的地经纬度（只有距离测量时支持|号分隔多个）
     *
     * Generated from protobuf field <code>string destination = 2;</code>
     */
    protected $destination = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $origin
     *          出发点经纬度（只有距离测量时支持|号分隔多个）
     *     @type string $destination
     *          目的地经纬度（只有距离测量时支持|号分隔多个）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Amap::initOnce();
        parent::__construct($data);
    }

    /**
     *出发点经纬度（只有距离测量时支持|号分隔多个）
     *
     * Generated from protobuf field <code>string origin = 1;</code>
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     *出发点经纬度（只有距离测量时支持|号分隔多个）
     *
     * Generated from protobuf field <code>string origin = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin = $var;

        return $this;
    }

    /**
     *目的地经纬度（只有距离测量时支持|号分隔多个）
     *
     * Generated from protobuf field <code>string destination = 2;</code>
     * @return string
     */
    public function getDestination()
    {
        return $this->destination;
    }

    /**
     *目的地经纬度（只有距离测量时支持|号分隔多个）
     *
     * Generated from protobuf field <code>string destination = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDestination($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination = $var;

        return $this;
    }

}

