<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/amap.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *高德返回结果
 *
 * Generated from protobuf message <code>proto.AmapResponse</code>
 */
class AmapResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *消息体
     *
     * Generated from protobuf field <code>optional .google.protobuf.Any data = 1;</code>
     */
    protected $data = null;
    /**
     *高德原始返回json
     *
     * Generated from protobuf field <code>optional string amapJson = 2;</code>
     */
    protected $amapJson = null;
    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 3;</code>
     */
    protected $requestId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Any $data
     *          消息体
     *     @type string $amapJson
     *          高德原始返回json
     *     @type string $requestId
     *          请求ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Amap::initOnce();
        parent::__construct($data);
    }

    /**
     *消息体
     *
     * Generated from protobuf field <code>optional .google.protobuf.Any data = 1;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     *消息体
     *
     * Generated from protobuf field <code>optional .google.protobuf.Any data = 1;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->data = $var;

        return $this;
    }

    /**
     *高德原始返回json
     *
     * Generated from protobuf field <code>optional string amapJson = 2;</code>
     * @return string
     */
    public function getAmapJson()
    {
        return isset($this->amapJson) ? $this->amapJson : '';
    }

    public function hasAmapJson()
    {
        return isset($this->amapJson);
    }

    public function clearAmapJson()
    {
        unset($this->amapJson);
    }

    /**
     *高德原始返回json
     *
     * Generated from protobuf field <code>optional string amapJson = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAmapJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->amapJson = $var;

        return $this;
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 3;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->requestId;
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestId = $var;

        return $this;
    }

}

