<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/amap.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *AmapRegeoParam 逆地理编码查询参数
 *
 * Generated from protobuf message <code>proto.AmapRegeoParam</code>
 */
class AmapRegeoParam extends \Google\Protobuf\Internal\Message
{
    /**
     *经度在前，纬度在后，经纬度间以“,”分割，经纬度小数点后不要超过 6 位。如果需要解析多个经纬度的话，请用"|"进行间隔，并且将 batch 参数设置为 true，最多支持传入 20 对坐标点。每对点坐标之间用"|"分割
     *
     * Generated from protobuf field <code>string location = 1;</code>
     */
    protected $location = '';
    /**
     *返回附近POI类型，extensions 参数为 all 时才生效
     *
     * Generated from protobuf field <code>string poitype = 2;</code>
     */
    protected $poitype = '';
    /**
     *搜索半径
     *
     * Generated from protobuf field <code>string radius = 3;</code>
     */
    protected $radius = '';
    /**
     *返回结果控制
     *
     * Generated from protobuf field <code>string extensions = 4;</code>
     */
    protected $extensions = '';
    /**
     *批量查询控制，batch 参数设置为 true 时进行批量查询操作，最多支持 20 个经纬度点进行批量地址查询操作
     *
     * Generated from protobuf field <code>bool batch = 5;</code>
     */
    protected $batch = false;
    /**
     *道路等级  extensions 参数为 all 时才生效。可选值：0，1
     *
     * Generated from protobuf field <code>string roadlevel = 6;</code>
     */
    protected $roadlevel = '';
    /**
     *是否优化POI返回顺序 0：不对召回的排序策略进行干扰。1：综合大数据分析将居家相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。2：综合大数据分析将公司相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。
     *
     * Generated from protobuf field <code>int32 homeorcorp = 7;</code>
     */
    protected $homeorcorp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $location
     *          经度在前，纬度在后，经纬度间以“,”分割，经纬度小数点后不要超过 6 位。如果需要解析多个经纬度的话，请用"|"进行间隔，并且将 batch 参数设置为 true，最多支持传入 20 对坐标点。每对点坐标之间用"|"分割
     *     @type string $poitype
     *          返回附近POI类型，extensions 参数为 all 时才生效
     *     @type string $radius
     *          搜索半径
     *     @type string $extensions
     *          返回结果控制
     *     @type bool $batch
     *          批量查询控制，batch 参数设置为 true 时进行批量查询操作，最多支持 20 个经纬度点进行批量地址查询操作
     *     @type string $roadlevel
     *          道路等级  extensions 参数为 all 时才生效。可选值：0，1
     *     @type int $homeorcorp
     *          是否优化POI返回顺序 0：不对召回的排序策略进行干扰。1：综合大数据分析将居家相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。2：综合大数据分析将公司相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Amap::initOnce();
        parent::__construct($data);
    }

    /**
     *经度在前，纬度在后，经纬度间以“,”分割，经纬度小数点后不要超过 6 位。如果需要解析多个经纬度的话，请用"|"进行间隔，并且将 batch 参数设置为 true，最多支持传入 20 对坐标点。每对点坐标之间用"|"分割
     *
     * Generated from protobuf field <code>string location = 1;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     *经度在前，纬度在后，经纬度间以“,”分割，经纬度小数点后不要超过 6 位。如果需要解析多个经纬度的话，请用"|"进行间隔，并且将 batch 参数设置为 true，最多支持传入 20 对坐标点。每对点坐标之间用"|"分割
     *
     * Generated from protobuf field <code>string location = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;

        return $this;
    }

    /**
     *返回附近POI类型，extensions 参数为 all 时才生效
     *
     * Generated from protobuf field <code>string poitype = 2;</code>
     * @return string
     */
    public function getPoitype()
    {
        return $this->poitype;
    }

    /**
     *返回附近POI类型，extensions 参数为 all 时才生效
     *
     * Generated from protobuf field <code>string poitype = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPoitype($var)
    {
        GPBUtil::checkString($var, True);
        $this->poitype = $var;

        return $this;
    }

    /**
     *搜索半径
     *
     * Generated from protobuf field <code>string radius = 3;</code>
     * @return string
     */
    public function getRadius()
    {
        return $this->radius;
    }

    /**
     *搜索半径
     *
     * Generated from protobuf field <code>string radius = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRadius($var)
    {
        GPBUtil::checkString($var, True);
        $this->radius = $var;

        return $this;
    }

    /**
     *返回结果控制
     *
     * Generated from protobuf field <code>string extensions = 4;</code>
     * @return string
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     *返回结果控制
     *
     * Generated from protobuf field <code>string extensions = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkString($var, True);
        $this->extensions = $var;

        return $this;
    }

    /**
     *批量查询控制，batch 参数设置为 true 时进行批量查询操作，最多支持 20 个经纬度点进行批量地址查询操作
     *
     * Generated from protobuf field <code>bool batch = 5;</code>
     * @return bool
     */
    public function getBatch()
    {
        return $this->batch;
    }

    /**
     *批量查询控制，batch 参数设置为 true 时进行批量查询操作，最多支持 20 个经纬度点进行批量地址查询操作
     *
     * Generated from protobuf field <code>bool batch = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBatch($var)
    {
        GPBUtil::checkBool($var);
        $this->batch = $var;

        return $this;
    }

    /**
     *道路等级  extensions 参数为 all 时才生效。可选值：0，1
     *
     * Generated from protobuf field <code>string roadlevel = 6;</code>
     * @return string
     */
    public function getRoadlevel()
    {
        return $this->roadlevel;
    }

    /**
     *道路等级  extensions 参数为 all 时才生效。可选值：0，1
     *
     * Generated from protobuf field <code>string roadlevel = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRoadlevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->roadlevel = $var;

        return $this;
    }

    /**
     *是否优化POI返回顺序 0：不对召回的排序策略进行干扰。1：综合大数据分析将居家相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。2：综合大数据分析将公司相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。
     *
     * Generated from protobuf field <code>int32 homeorcorp = 7;</code>
     * @return int
     */
    public function getHomeorcorp()
    {
        return $this->homeorcorp;
    }

    /**
     *是否优化POI返回顺序 0：不对召回的排序策略进行干扰。1：综合大数据分析将居家相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。2：综合大数据分析将公司相关的 POI 内容优先返回，即优化返回结果中 pois 字段的poi顺序。
     *
     * Generated from protobuf field <code>int32 homeorcorp = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setHomeorcorp($var)
    {
        GPBUtil::checkInt32($var);
        $this->homeorcorp = $var;

        return $this;
    }

}

