<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 微信小程序解密后 用户信息结构体
 *
 * Generated from protobuf message <code>proto.AppletUserInfoResponse</code>
 */
class AppletUserInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string openId = 1;</code>
     */
    protected $openId = '';
    /**
     * Generated from protobuf field <code>string nickName = 2;</code>
     */
    protected $nickName = '';
    /**
     * Generated from protobuf field <code>int32 gender = 3;</code>
     */
    protected $gender = 0;
    /**
     * Generated from protobuf field <code>string city = 4;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string province = 5;</code>
     */
    protected $province = '';
    /**
     * Generated from protobuf field <code>string country = 6;</code>
     */
    protected $country = '';
    /**
     * Generated from protobuf field <code>string avatarUrl = 7;</code>
     */
    protected $avatarUrl = '';
    /**
     * Generated from protobuf field <code>string unionId = 8;</code>
     */
    protected $unionId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $openId
     *     @type string $nickName
     *     @type int $gender
     *     @type string $city
     *     @type string $province
     *     @type string $country
     *     @type string $avatarUrl
     *     @type string $unionId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string openId = 1;</code>
     * @return string
     */
    public function getOpenId()
    {
        return $this->openId;
    }

    /**
     * Generated from protobuf field <code>string openId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->openId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickName = 2;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->nickName;
    }

    /**
     * Generated from protobuf field <code>string nickName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 gender = 3;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>int32 gender = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->gender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 4;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string province = 5;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Generated from protobuf field <code>string province = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->province = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 6;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string avatarUrl = 7;</code>
     * @return string
     */
    public function getAvatarUrl()
    {
        return $this->avatarUrl;
    }

    /**
     * Generated from protobuf field <code>string avatarUrl = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatarUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatarUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unionId = 8;</code>
     * @return string
     */
    public function getUnionId()
    {
        return $this->unionId;
    }

    /**
     * Generated from protobuf field <code>string unionId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->unionId = $var;

        return $this;
    }

}

