<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dyvms.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *语音验证码参数 
 *
 * Generated from protobuf message <code>proto.CallTTSParam</code>
 */
class CallTTSParam extends \Google\Protobuf\Internal\Message
{
    /**
     *接收语音通知的手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     */
    protected $phone = '';
    /**
     *已通过审核的语音验证码模板ID
     *
     * Generated from protobuf field <code>string ttsCode = 2;</code>
     */
    protected $ttsCode = '';
    /**
     *模板中的变量参数
     *
     * Generated from protobuf field <code>.google.protobuf.Any ttsParam = 3;</code>
     */
    protected $ttsParam = null;
    /**
     *一通电话内语音通知内容的播放次数
     *
     * Generated from protobuf field <code>int32 playTimes = 4;</code>
     */
    protected $playTimes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phone
     *          接收语音通知的手机号码
     *     @type string $ttsCode
     *          已通过审核的语音验证码模板ID
     *     @type \Google\Protobuf\Any $ttsParam
     *          模板中的变量参数
     *     @type int $playTimes
     *          一通电话内语音通知内容的播放次数
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Dyvms::initOnce();
        parent::__construct($data);
    }

    /**
     *接收语音通知的手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *接收语音通知的手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     *已通过审核的语音验证码模板ID
     *
     * Generated from protobuf field <code>string ttsCode = 2;</code>
     * @return string
     */
    public function getTtsCode()
    {
        return $this->ttsCode;
    }

    /**
     *已通过审核的语音验证码模板ID
     *
     * Generated from protobuf field <code>string ttsCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTtsCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ttsCode = $var;

        return $this;
    }

    /**
     *模板中的变量参数
     *
     * Generated from protobuf field <code>.google.protobuf.Any ttsParam = 3;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getTtsParam()
    {
        return $this->ttsParam;
    }

    public function hasTtsParam()
    {
        return isset($this->ttsParam);
    }

    public function clearTtsParam()
    {
        unset($this->ttsParam);
    }

    /**
     *模板中的变量参数
     *
     * Generated from protobuf field <code>.google.protobuf.Any ttsParam = 3;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setTtsParam($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->ttsParam = $var;

        return $this;
    }

    /**
     *一通电话内语音通知内容的播放次数
     *
     * Generated from protobuf field <code>int32 playTimes = 4;</code>
     * @return int
     */
    public function getPlayTimes()
    {
        return $this->playTimes;
    }

    /**
     *一通电话内语音通知内容的播放次数
     *
     * Generated from protobuf field <code>int32 playTimes = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPlayTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->playTimes = $var;

        return $this;
    }

}

