<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dyvms.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *呼叫结果
 *
 * Generated from protobuf message <code>proto.CallResponse</code>
 */
class CallResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 1;</code>
     */
    protected $requestId = '';
    /**
     *状态码的描述。
     *
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     *呼叫序列号
     *
     * Generated from protobuf field <code>string callId = 3;</code>
     */
    protected $callId = '';
    /**
     *请求状态码，返回OK代表请求成功
     *
     * Generated from protobuf field <code>string code = 4;</code>
     */
    protected $code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requestId
     *          请求ID
     *     @type string $message
     *          状态码的描述。
     *     @type string $callId
     *          呼叫序列号
     *     @type string $code
     *          请求状态码，返回OK代表请求成功
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Dyvms::initOnce();
        parent::__construct($data);
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 1;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->requestId;
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string requestId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestId = $var;

        return $this;
    }

    /**
     *状态码的描述。
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     *状态码的描述。
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     *呼叫序列号
     *
     * Generated from protobuf field <code>string callId = 3;</code>
     * @return string
     */
    public function getCallId()
    {
        return $this->callId;
    }

    /**
     *呼叫序列号
     *
     * Generated from protobuf field <code>string callId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCallId($var)
    {
        GPBUtil::checkString($var, True);
        $this->callId = $var;

        return $this;
    }

    /**
     *请求状态码，返回OK代表请求成功
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *请求状态码，返回OK代表请求成功
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

}

