<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dyvms.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *语音呼叫（录音文件）
 *
 * Generated from protobuf message <code>proto.CallVoiceParam</code>
 */
class CallVoiceParam extends \Google\Protobuf\Internal\Message
{
    /**
     *接收语音通知的手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     */
    protected $phone = '';
    /**
     *语音文件的语音ID
     *
     * Generated from protobuf field <code>string voiceCode = 2;</code>
     */
    protected $voiceCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phone
     *          接收语音通知的手机号码
     *     @type string $voiceCode
     *          语音文件的语音ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Dyvms::initOnce();
        parent::__construct($data);
    }

    /**
     *接收语音通知的手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *接收语音通知的手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     *语音文件的语音ID
     *
     * Generated from protobuf field <code>string voiceCode = 2;</code>
     * @return string
     */
    public function getVoiceCode()
    {
        return $this->voiceCode;
    }

    /**
     *语音文件的语音ID
     *
     * Generated from protobuf field <code>string voiceCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVoiceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->voiceCode = $var;

        return $this;
    }

}

