<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *客户端列表
 *
 * Generated from protobuf message <code>proto.ClientList</code>
 */
class ClientList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string clients = 1;</code>
     */
    private $clients;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $clients
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Chat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string clients = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClients()
    {
        return $this->clients;
    }

    /**
     * Generated from protobuf field <code>repeated string clients = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->clients = $arr;

        return $this;
    }

}

