<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/addr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *地址补全
 *
 * Generated from protobuf message <code>proto.CompleteAddressResponse</code>
 */
class CompleteAddressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *完整地址
     *
     * Generated from protobuf field <code>string complete = 1;</code>
     */
    protected $complete = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $complete
     *          完整地址
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Addr::initOnce();
        parent::__construct($data);
    }

    /**
     *完整地址
     *
     * Generated from protobuf field <code>string complete = 1;</code>
     * @return string
     */
    public function getComplete()
    {
        return $this->complete;
    }

    /**
     *完整地址
     *
     * Generated from protobuf field <code>string complete = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setComplete($var)
    {
        GPBUtil::checkString($var, True);
        $this->complete = $var;

        return $this;
    }

}

