<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/amap.proto

namespace Proto;

use UnexpectedValueException;

/**
 *距离测量方式
 *
 * Protobuf type <code>proto.DistanceType</code>
 */
class DistanceType
{
    /**
     *直线距离
     *
     * Generated from protobuf enum <code>straight = 0;</code>
     */
    const straight = 0;
    /**
     *驾车导航距离（仅支持国内坐标）
     *
     * Generated from protobuf enum <code>driving = 1;</code>
     */
    const driving = 1;
    /**
     *骑行规划距离（自己实现）
     *
     * Generated from protobuf enum <code>cycling = 2;</code>
     */
    const cycling = 2;
    /**
     *步行规划距离（仅支持5km之间的距离）
     *
     * Generated from protobuf enum <code>walking = 3;</code>
     */
    const walking = 3;

    private static $valueToName = [
        self::straight => 'straight',
        self::driving => 'driving',
        self::cycling => 'cycling',
        self::walking => 'walking',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

