<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/addr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *物流面单信息提取
 *
 * Generated from protobuf message <code>proto.ExpressExtractResponse</code>
 */
class ExpressExtractResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *房屋信息
     *
     * Generated from protobuf field <code>string houseInfo = 1;</code>
     */
    protected $houseInfo = '';
    /**
     *poi信息
     *
     * Generated from protobuf field <code>string poiInfo = 2;</code>
     */
    protected $poiInfo = '';
    /**
     *级行政区划，镇、街道、乡等
     *
     * Generated from protobuf field <code>string town = 3;</code>
     */
    protected $town = '';
    /**
     *地级行政区划，地级市、地区、自治州等
     *
     * Generated from protobuf field <code>string city = 4;</code>
     */
    protected $city = '';
    /**
     *县级行政区划，市辖区、县级市、县等
     *
     * Generated from protobuf field <code>string district = 5;</code>
     */
    protected $district = '';
    /**
     *联系电话
     *
     * Generated from protobuf field <code>string tel = 6;</code>
     */
    protected $tel = '';
    /**
     *地址信息
     *
     * Generated from protobuf field <code>string addrInfo = 7;</code>
     */
    protected $addrInfo = '';
    /**
     *姓名
     *
     * Generated from protobuf field <code>string per = 8;</code>
     */
    protected $per = '';
    /**
     *省级行政区划，省、自治区、直辖市
     *
     * Generated from protobuf field <code>string prov = 9;</code>
     */
    protected $prov = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $houseInfo
     *          房屋信息
     *     @type string $poiInfo
     *          poi信息
     *     @type string $town
     *          级行政区划，镇、街道、乡等
     *     @type string $city
     *          地级行政区划，地级市、地区、自治州等
     *     @type string $district
     *          县级行政区划，市辖区、县级市、县等
     *     @type string $tel
     *          联系电话
     *     @type string $addrInfo
     *          地址信息
     *     @type string $per
     *          姓名
     *     @type string $prov
     *          省级行政区划，省、自治区、直辖市
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Addr::initOnce();
        parent::__construct($data);
    }

    /**
     *房屋信息
     *
     * Generated from protobuf field <code>string houseInfo = 1;</code>
     * @return string
     */
    public function getHouseInfo()
    {
        return $this->houseInfo;
    }

    /**
     *房屋信息
     *
     * Generated from protobuf field <code>string houseInfo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHouseInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->houseInfo = $var;

        return $this;
    }

    /**
     *poi信息
     *
     * Generated from protobuf field <code>string poiInfo = 2;</code>
     * @return string
     */
    public function getPoiInfo()
    {
        return $this->poiInfo;
    }

    /**
     *poi信息
     *
     * Generated from protobuf field <code>string poiInfo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPoiInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->poiInfo = $var;

        return $this;
    }

    /**
     *级行政区划，镇、街道、乡等
     *
     * Generated from protobuf field <code>string town = 3;</code>
     * @return string
     */
    public function getTown()
    {
        return $this->town;
    }

    /**
     *级行政区划，镇、街道、乡等
     *
     * Generated from protobuf field <code>string town = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTown($var)
    {
        GPBUtil::checkString($var, True);
        $this->town = $var;

        return $this;
    }

    /**
     *地级行政区划，地级市、地区、自治州等
     *
     * Generated from protobuf field <code>string city = 4;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     *地级行政区划，地级市、地区、自治州等
     *
     * Generated from protobuf field <code>string city = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     *县级行政区划，市辖区、县级市、县等
     *
     * Generated from protobuf field <code>string district = 5;</code>
     * @return string
     */
    public function getDistrict()
    {
        return $this->district;
    }

    /**
     *县级行政区划，市辖区、县级市、县等
     *
     * Generated from protobuf field <code>string district = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDistrict($var)
    {
        GPBUtil::checkString($var, True);
        $this->district = $var;

        return $this;
    }

    /**
     *联系电话
     *
     * Generated from protobuf field <code>string tel = 6;</code>
     * @return string
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     *联系电话
     *
     * Generated from protobuf field <code>string tel = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTel($var)
    {
        GPBUtil::checkString($var, True);
        $this->tel = $var;

        return $this;
    }

    /**
     *地址信息
     *
     * Generated from protobuf field <code>string addrInfo = 7;</code>
     * @return string
     */
    public function getAddrInfo()
    {
        return $this->addrInfo;
    }

    /**
     *地址信息
     *
     * Generated from protobuf field <code>string addrInfo = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddrInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->addrInfo = $var;

        return $this;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string per = 8;</code>
     * @return string
     */
    public function getPer()
    {
        return $this->per;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string per = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPer($var)
    {
        GPBUtil::checkString($var, True);
        $this->per = $var;

        return $this;
    }

    /**
     *省级行政区划，省、自治区、直辖市
     *
     * Generated from protobuf field <code>string prov = 9;</code>
     * @return string
     */
    public function getProv()
    {
        return $this->prov;
    }

    /**
     *省级行政区划，省、自治区、直辖市
     *
     * Generated from protobuf field <code>string prov = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setProv($var)
    {
        GPBUtil::checkString($var, True);
        $this->prov = $var;

        return $this;
    }

}

