<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/goodstech.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GoodsTenchResponse</code>
 */
class GoodsTenchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *数组
     *
     * Generated from protobuf field <code>repeated .proto.ClassifyCommodity categorys = 1;</code>
     */
    private $categorys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\ClassifyCommodity[]|\Google\Protobuf\Internal\RepeatedField $categorys
     *          数组
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Goodstech::initOnce();
        parent::__construct($data);
    }

    /**
     *数组
     *
     * Generated from protobuf field <code>repeated .proto.ClassifyCommodity categorys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCategorys()
    {
        return $this->categorys;
    }

    /**
     *数组
     *
     * Generated from protobuf field <code>repeated .proto.ClassifyCommodity categorys = 1;</code>
     * @param \Proto\ClassifyCommodity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCategorys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\ClassifyCommodity::class);
        $this->categorys = $arr;

        return $this;
    }

}

