<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/goodstech.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GoodsTenchParam</code>
 */
class GoodsTenchParam extends \Google\Protobuf\Internal\Message
{
    /**
     *图片识别地址
     *
     * Generated from protobuf field <code>string photoUrl = 1;</code>
     */
    protected $photoUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $photoUrl
     *          图片识别地址
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Goodstech::initOnce();
        parent::__construct($data);
    }

    /**
     *图片识别地址
     *
     * Generated from protobuf field <code>string photoUrl = 1;</code>
     * @return string
     */
    public function getPhotoUrl()
    {
        return $this->photoUrl;
    }

    /**
     *图片识别地址
     *
     * Generated from protobuf field <code>string photoUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->photoUrl = $var;

        return $this;
    }

}

