<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *群组列表
 *
 * Generated from protobuf message <code>proto.GroupList</code>
 */
class GroupList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string groups = 1;</code>
     */
    private $groups;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $groups
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Chat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string groups = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Generated from protobuf field <code>repeated string groups = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->groups = $arr;

        return $this;
    }

}

