<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *群组信息
 *
 * Generated from protobuf message <code>proto.GroupInfo</code>
 */
class GroupInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *客户端
     *
     * Generated from protobuf field <code>string client = 1;</code>
     */
    protected $client = '';
    /**
     *群组名称
     *
     * Generated from protobuf field <code>string groupName = 2;</code>
     */
    protected $groupName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client
     *          客户端
     *     @type string $groupName
     *          群组名称
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Chat::initOnce();
        parent::__construct($data);
    }

    /**
     *客户端
     *
     * Generated from protobuf field <code>string client = 1;</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     *客户端
     *
     * Generated from protobuf field <code>string client = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkString($var, True);
        $this->client = $var;

        return $this;
    }

    /**
     *群组名称
     *
     * Generated from protobuf field <code>string groupName = 2;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->groupName;
    }

    /**
     *群组名称
     *
     * Generated from protobuf field <code>string groupName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupName = $var;

        return $this;
    }

}

