<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ocr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *身份证反面信息
 *
 * Generated from protobuf message <code>proto.IdentityCardBack</code>
 */
class IdentityCardBack extends \Google\Protobuf\Internal\Message
{
    /**
     *有效期结束时间，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string endDate = 1;</code>
     */
    protected $endDate = null;
    /**
     *签发机关
     *
     * Generated from protobuf field <code>optional string issue = 2;</code>
     */
    protected $issue = null;
    /**
     *有效期起始时间，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string startDate = 3;</code>
     */
    protected $startDate = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $endDate
     *          有效期结束时间，格式：YYYYMMDD
     *     @type string $issue
     *          签发机关
     *     @type string $startDate
     *          有效期起始时间，格式：YYYYMMDD
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     *有效期结束时间，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string endDate = 1;</code>
     * @return string
     */
    public function getEndDate()
    {
        return isset($this->endDate) ? $this->endDate : '';
    }

    public function hasEndDate()
    {
        return isset($this->endDate);
    }

    public function clearEndDate()
    {
        unset($this->endDate);
    }

    /**
     *有效期结束时间，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string endDate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->endDate = $var;

        return $this;
    }

    /**
     *签发机关
     *
     * Generated from protobuf field <code>optional string issue = 2;</code>
     * @return string
     */
    public function getIssue()
    {
        return isset($this->issue) ? $this->issue : '';
    }

    public function hasIssue()
    {
        return isset($this->issue);
    }

    public function clearIssue()
    {
        unset($this->issue);
    }

    /**
     *签发机关
     *
     * Generated from protobuf field <code>optional string issue = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIssue($var)
    {
        GPBUtil::checkString($var, True);
        $this->issue = $var;

        return $this;
    }

    /**
     *有效期起始时间，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string startDate = 3;</code>
     * @return string
     */
    public function getStartDate()
    {
        return isset($this->startDate) ? $this->startDate : '';
    }

    public function hasStartDate()
    {
        return isset($this->startDate);
    }

    public function clearStartDate()
    {
        unset($this->startDate);
    }

    /**
     *有效期起始时间，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string startDate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->startDate = $var;

        return $this;
    }

}

