<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ocr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *身份证正面信息
 *
 * Generated from protobuf message <code>proto.IdentityCardFace</code>
 */
class IdentityCardFace extends \Google\Protobuf\Internal\Message
{
    /**
     *出生日期，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string birthDate = 1;</code>
     */
    protected $birthDate = null;
    /**
     *性别
     *
     * Generated from protobuf field <code>optional string gender = 2;</code>
     */
    protected $gender = null;
    /**
     *地址信息
     *
     * Generated from protobuf field <code>optional string address = 3;</code>
     */
    protected $address = null;
    /**
     *民族
     *
     * Generated from protobuf field <code>optional string nationality = 4;</code>
     */
    protected $nationality = null;
    /**
     *姓名
     *
     * Generated from protobuf field <code>optional string name = 5;</code>
     */
    protected $name = null;
    /**
     *身份证号码
     *
     * Generated from protobuf field <code>optional string idNumber = 6;</code>
     */
    protected $idNumber = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $birthDate
     *          出生日期，格式：YYYYMMDD
     *     @type string $gender
     *          性别
     *     @type string $address
     *          地址信息
     *     @type string $nationality
     *          民族
     *     @type string $name
     *          姓名
     *     @type string $idNumber
     *          身份证号码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     *出生日期，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string birthDate = 1;</code>
     * @return string
     */
    public function getBirthDate()
    {
        return isset($this->birthDate) ? $this->birthDate : '';
    }

    public function hasBirthDate()
    {
        return isset($this->birthDate);
    }

    public function clearBirthDate()
    {
        unset($this->birthDate);
    }

    /**
     *出生日期，格式：YYYYMMDD
     *
     * Generated from protobuf field <code>optional string birthDate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBirthDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->birthDate = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>optional string gender = 2;</code>
     * @return string
     */
    public function getGender()
    {
        return isset($this->gender) ? $this->gender : '';
    }

    public function hasGender()
    {
        return isset($this->gender);
    }

    public function clearGender()
    {
        unset($this->gender);
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>optional string gender = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkString($var, True);
        $this->gender = $var;

        return $this;
    }

    /**
     *地址信息
     *
     * Generated from protobuf field <code>optional string address = 3;</code>
     * @return string
     */
    public function getAddress()
    {
        return isset($this->address) ? $this->address : '';
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     *地址信息
     *
     * Generated from protobuf field <code>optional string address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     *民族
     *
     * Generated from protobuf field <code>optional string nationality = 4;</code>
     * @return string
     */
    public function getNationality()
    {
        return isset($this->nationality) ? $this->nationality : '';
    }

    public function hasNationality()
    {
        return isset($this->nationality);
    }

    public function clearNationality()
    {
        unset($this->nationality);
    }

    /**
     *民族
     *
     * Generated from protobuf field <code>optional string nationality = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNationality($var)
    {
        GPBUtil::checkString($var, True);
        $this->nationality = $var;

        return $this;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>optional string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>optional string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *身份证号码
     *
     * Generated from protobuf field <code>optional string idNumber = 6;</code>
     * @return string
     */
    public function getIdNumber()
    {
        return isset($this->idNumber) ? $this->idNumber : '';
    }

    public function hasIdNumber()
    {
        return isset($this->idNumber);
    }

    public function clearIdNumber()
    {
        unset($this->idNumber);
    }

    /**
     *身份证号码
     *
     * Generated from protobuf field <code>optional string idNumber = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIdNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->idNumber = $var;

        return $this;
    }

}

