<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/jpush.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *推送返回结果
 *
 * Generated from protobuf message <code>proto.JPushResponse</code>
 */
class JPushResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sendno = 1;</code>
     */
    protected $sendno = '';
    /**
     * Generated from protobuf field <code>string msgId = 2;</code>
     */
    protected $msgId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sendno
     *     @type string $msgId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Jpush::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sendno = 1;</code>
     * @return string
     */
    public function getSendno()
    {
        return $this->sendno;
    }

    /**
     * Generated from protobuf field <code>string sendno = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSendno($var)
    {
        GPBUtil::checkString($var, True);
        $this->sendno = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msgId = 2;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msgId;
    }

    /**
     * Generated from protobuf field <code>string msgId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgId = $var;

        return $this;
    }

}

