<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/jpush.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *极光推送
 *
 * Generated from protobuf message <code>proto.JPushAliasParam</code>
 */
class JPushAliasParam extends \Google\Protobuf\Internal\Message
{
    /**
     *推送内容
     *
     * Generated from protobuf field <code>string content = 1;</code>
     */
    protected $content = '';
    /**
     *声音文件的名称
     *
     * Generated from protobuf field <code>string sound = 2;</code>
     */
    protected $sound = '';
    /**
     *推送别名，数组
     *
     * Generated from protobuf field <code>repeated string alias = 3;</code>
     */
    private $alias;
    /**
     *扩展信息
     *
     * Generated from protobuf field <code>.google.protobuf.Any extinfo = 4;</code>
     */
    protected $extinfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $content
     *          推送内容
     *     @type string $sound
     *          声音文件的名称
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $alias
     *          推送别名，数组
     *     @type \Google\Protobuf\Any $extinfo
     *          扩展信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Jpush::initOnce();
        parent::__construct($data);
    }

    /**
     *推送内容
     *
     * Generated from protobuf field <code>string content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *推送内容
     *
     * Generated from protobuf field <code>string content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *声音文件的名称
     *
     * Generated from protobuf field <code>string sound = 2;</code>
     * @return string
     */
    public function getSound()
    {
        return $this->sound;
    }

    /**
     *声音文件的名称
     *
     * Generated from protobuf field <code>string sound = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSound($var)
    {
        GPBUtil::checkString($var, True);
        $this->sound = $var;

        return $this;
    }

    /**
     *推送别名，数组
     *
     * Generated from protobuf field <code>repeated string alias = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     *推送别名，数组
     *
     * Generated from protobuf field <code>repeated string alias = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAlias($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->alias = $arr;

        return $this;
    }

    /**
     *扩展信息
     *
     * Generated from protobuf field <code>.google.protobuf.Any extinfo = 4;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getExtinfo()
    {
        return $this->extinfo;
    }

    public function hasExtinfo()
    {
        return isset($this->extinfo);
    }

    public function clearExtinfo()
    {
        unset($this->extinfo);
    }

    /**
     *扩展信息
     *
     * Generated from protobuf field <code>.google.protobuf.Any extinfo = 4;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setExtinfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->extinfo = $var;

        return $this;
    }

}

