<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *二维码线条颜色
 *
 * Generated from protobuf message <code>proto.LineColorParam</code>
 */
class LineColorParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string r = 1;</code>
     */
    protected $r = '';
    /**
     * Generated from protobuf field <code>string g = 2;</code>
     */
    protected $g = '';
    /**
     * Generated from protobuf field <code>string b = 3;</code>
     */
    protected $b = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $r
     *     @type string $g
     *     @type string $b
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string r = 1;</code>
     * @return string
     */
    public function getR()
    {
        return $this->r;
    }

    /**
     * Generated from protobuf field <code>string r = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setR($var)
    {
        GPBUtil::checkString($var, True);
        $this->r = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string g = 2;</code>
     * @return string
     */
    public function getG()
    {
        return $this->g;
    }

    /**
     * Generated from protobuf field <code>string g = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setG($var)
    {
        GPBUtil::checkString($var, True);
        $this->g = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b = 3;</code>
     * @return string
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * Generated from protobuf field <code>string b = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setB($var)
    {
        GPBUtil::checkString($var, True);
        $this->b = $var;

        return $this;
    }

}

