<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mqtt.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.MqttVoiceNoticeParam</code>
 */
class MqttVoiceNoticeParam extends \Google\Protobuf\Internal\Message
{
    /**
     *打印机序列号
     *
     * Generated from protobuf field <code>string mqttClientId = 1;</code>
     */
    protected $mqttClientId = '';
    /**
     *播报内容
     *
     * Generated from protobuf field <code>string noticeText = 2;</code>
     */
    protected $noticeText = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mqttClientId
     *          打印机序列号
     *     @type string $noticeText
     *          播报内容
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Mqtt::initOnce();
        parent::__construct($data);
    }

    /**
     *打印机序列号
     *
     * Generated from protobuf field <code>string mqttClientId = 1;</code>
     * @return string
     */
    public function getMqttClientId()
    {
        return $this->mqttClientId;
    }

    /**
     *打印机序列号
     *
     * Generated from protobuf field <code>string mqttClientId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMqttClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->mqttClientId = $var;

        return $this;
    }

    /**
     *播报内容
     *
     * Generated from protobuf field <code>string noticeText = 2;</code>
     * @return string
     */
    public function getNoticeText()
    {
        return $this->noticeText;
    }

    /**
     *播报内容
     *
     * Generated from protobuf field <code>string noticeText = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNoticeText($var)
    {
        GPBUtil::checkString($var, True);
        $this->noticeText = $var;

        return $this;
    }

}

