<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mqtt.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\MqttClientsResponse\MqttClients instead.
     * @deprecated
     */
    class MqttClientsResponse_MqttClients {}
}
class_exists(MqttClientsResponse\MqttClients::class);
@trigger_error('Proto\MqttClientsResponse_MqttClients is deprecated and will be removed in the next major release. Use Proto\MqttClientsResponse\MqttClients instead', E_USER_DEPRECATED);

