<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mqtt.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.MqttQueryClinetsParam</code>
 */
class MqttQueryClinetsParam extends \Google\Protobuf\Internal\Message
{
    /**
     *分页
     *
     * Generated from protobuf field <code>optional .proto.PageParam page = 1;</code>
     */
    protected $page = null;
    /**
     *客户端ID
     *
     * Generated from protobuf field <code>optional string clientid = 2;</code>
     */
    protected $clientid = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\PageParam $page
     *          分页
     *     @type string $clientid
     *          客户端ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Mqtt::initOnce();
        parent::__construct($data);
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>optional .proto.PageParam page = 1;</code>
     * @return \Proto\PageParam|null
     */
    public function getPage()
    {
        return $this->page;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>optional .proto.PageParam page = 1;</code>
     * @param \Proto\PageParam $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Proto\PageParam::class);
        $this->page = $var;

        return $this;
    }

    /**
     *客户端ID
     *
     * Generated from protobuf field <code>optional string clientid = 2;</code>
     * @return string
     */
    public function getClientid()
    {
        return isset($this->clientid) ? $this->clientid : '';
    }

    public function hasClientid()
    {
        return isset($this->clientid);
    }

    public function clearClientid()
    {
        unset($this->clientid);
    }

    /**
     *客户端ID
     *
     * Generated from protobuf field <code>optional string clientid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientid($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientid = $var;

        return $this;
    }

}

