<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mqtt.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.MqttClientsResponse</code>
 */
class MqttClientsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.MqttClientsResponse.MqttClients client = 1;</code>
     */
    private $client;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\MqttClientsResponse\MqttClients[]|\Google\Protobuf\Internal\RepeatedField $client
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Mqtt::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.MqttClientsResponse.MqttClients client = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.MqttClientsResponse.MqttClients client = 1;</code>
     * @param \Proto\MqttClientsResponse\MqttClients[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClient($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\MqttClientsResponse\MqttClients::class);
        $this->client = $arr;

        return $this;
    }

}

