<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mqtt.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.MqttPrintOrderParam</code>
 */
class MqttPrintOrderParam extends \Google\Protobuf\Internal\Message
{
    /**
     *打印机序列号
     *
     * Generated from protobuf field <code>string mqttClientId = 1;</code>
     */
    protected $mqttClientId = '';
    /**
     *打印份数
     *
     * Generated from protobuf field <code>int32 printNum = 2;</code>
     */
    protected $printNum = 0;
    /**
     *店铺名字
     *
     * Generated from protobuf field <code>string shopName = 3;</code>
     */
    protected $shopName = '';
    /**
     *订单标题
     *
     * Generated from protobuf field <code>string orderTitle = 4;</code>
     */
    protected $orderTitle = '';
    /**
     *订单号
     *
     * Generated from protobuf field <code>string orderSn = 5;</code>
     */
    protected $orderSn = '';
    /**
     *下单时间
     *
     * Generated from protobuf field <code>string orderTime = 6;</code>
     */
    protected $orderTime = '';
    /**
     *订单总金额
     *
     * Generated from protobuf field <code>string orderAmount = 7;</code>
     */
    protected $orderAmount = '';
    /**
     *商品列表
     *
     * Generated from protobuf field <code>repeated .proto.PrintGoods goodsList = 8;</code>
     */
    private $goodsList;
    /**
     *赠品列表
     *
     * Generated from protobuf field <code>repeated .proto.PrintGoods giftList = 9;</code>
     */
    private $giftList;
    /**
     *优惠列表(可选)
     *
     * Generated from protobuf field <code>repeated .proto.OtherAmount discount = 10;</code>
     */
    private $discount;
    /**
     *其它费用列表(可选)
     *
     * Generated from protobuf field <code>repeated .proto.OtherAmount otherAmount = 11;</code>
     */
    private $otherAmount;
    /**
     *预约时间，自提时间(可选)
     *
     * Generated from protobuf field <code>optional string orderBookTime = 12;</code>
     */
    protected $orderBookTime = null;
    /**
     *订单备注(可选)
     *
     * Generated from protobuf field <code>optional string orderRemarks = 13;</code>
     */
    protected $orderRemarks = null;
    /**
     *收货人姓名(可选)
     *
     * Generated from protobuf field <code>optional string toName = 14;</code>
     */
    protected $toName = null;
    /**
     *收货人地址(可选)
     *
     * Generated from protobuf field <code>optional string toAddress = 15;</code>
     */
    protected $toAddress = null;
    /**
     *收货人电话(可选)
     *
     * Generated from protobuf field <code>optional string toMobile = 16;</code>
     */
    protected $toMobile = null;
    /**
     *二维码显地址(可选)
     *
     * Generated from protobuf field <code>optional string qrCodeUrl = 17;</code>
     */
    protected $qrCodeUrl = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mqttClientId
     *          打印机序列号
     *     @type int $printNum
     *          打印份数
     *     @type string $shopName
     *          店铺名字
     *     @type string $orderTitle
     *          订单标题
     *     @type string $orderSn
     *          订单号
     *     @type string $orderTime
     *          下单时间
     *     @type string $orderAmount
     *          订单总金额
     *     @type \Proto\PrintGoods[]|\Google\Protobuf\Internal\RepeatedField $goodsList
     *          商品列表
     *     @type \Proto\PrintGoods[]|\Google\Protobuf\Internal\RepeatedField $giftList
     *          赠品列表
     *     @type \Proto\OtherAmount[]|\Google\Protobuf\Internal\RepeatedField $discount
     *          优惠列表(可选)
     *     @type \Proto\OtherAmount[]|\Google\Protobuf\Internal\RepeatedField $otherAmount
     *          其它费用列表(可选)
     *     @type string $orderBookTime
     *          预约时间，自提时间(可选)
     *     @type string $orderRemarks
     *          订单备注(可选)
     *     @type string $toName
     *          收货人姓名(可选)
     *     @type string $toAddress
     *          收货人地址(可选)
     *     @type string $toMobile
     *          收货人电话(可选)
     *     @type string $qrCodeUrl
     *          二维码显地址(可选)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Mqtt::initOnce();
        parent::__construct($data);
    }

    /**
     *打印机序列号
     *
     * Generated from protobuf field <code>string mqttClientId = 1;</code>
     * @return string
     */
    public function getMqttClientId()
    {
        return $this->mqttClientId;
    }

    /**
     *打印机序列号
     *
     * Generated from protobuf field <code>string mqttClientId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMqttClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->mqttClientId = $var;

        return $this;
    }

    /**
     *打印份数
     *
     * Generated from protobuf field <code>int32 printNum = 2;</code>
     * @return int
     */
    public function getPrintNum()
    {
        return $this->printNum;
    }

    /**
     *打印份数
     *
     * Generated from protobuf field <code>int32 printNum = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPrintNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->printNum = $var;

        return $this;
    }

    /**
     *店铺名字
     *
     * Generated from protobuf field <code>string shopName = 3;</code>
     * @return string
     */
    public function getShopName()
    {
        return $this->shopName;
    }

    /**
     *店铺名字
     *
     * Generated from protobuf field <code>string shopName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setShopName($var)
    {
        GPBUtil::checkString($var, True);
        $this->shopName = $var;

        return $this;
    }

    /**
     *订单标题
     *
     * Generated from protobuf field <code>string orderTitle = 4;</code>
     * @return string
     */
    public function getOrderTitle()
    {
        return $this->orderTitle;
    }

    /**
     *订单标题
     *
     * Generated from protobuf field <code>string orderTitle = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderTitle = $var;

        return $this;
    }

    /**
     *订单号
     *
     * Generated from protobuf field <code>string orderSn = 5;</code>
     * @return string
     */
    public function getOrderSn()
    {
        return $this->orderSn;
    }

    /**
     *订单号
     *
     * Generated from protobuf field <code>string orderSn = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderSn($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderSn = $var;

        return $this;
    }

    /**
     *下单时间
     *
     * Generated from protobuf field <code>string orderTime = 6;</code>
     * @return string
     */
    public function getOrderTime()
    {
        return $this->orderTime;
    }

    /**
     *下单时间
     *
     * Generated from protobuf field <code>string orderTime = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderTime = $var;

        return $this;
    }

    /**
     *订单总金额
     *
     * Generated from protobuf field <code>string orderAmount = 7;</code>
     * @return string
     */
    public function getOrderAmount()
    {
        return $this->orderAmount;
    }

    /**
     *订单总金额
     *
     * Generated from protobuf field <code>string orderAmount = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderAmount = $var;

        return $this;
    }

    /**
     *商品列表
     *
     * Generated from protobuf field <code>repeated .proto.PrintGoods goodsList = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGoodsList()
    {
        return $this->goodsList;
    }

    /**
     *商品列表
     *
     * Generated from protobuf field <code>repeated .proto.PrintGoods goodsList = 8;</code>
     * @param \Proto\PrintGoods[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGoodsList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\PrintGoods::class);
        $this->goodsList = $arr;

        return $this;
    }

    /**
     *赠品列表
     *
     * Generated from protobuf field <code>repeated .proto.PrintGoods giftList = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGiftList()
    {
        return $this->giftList;
    }

    /**
     *赠品列表
     *
     * Generated from protobuf field <code>repeated .proto.PrintGoods giftList = 9;</code>
     * @param \Proto\PrintGoods[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGiftList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\PrintGoods::class);
        $this->giftList = $arr;

        return $this;
    }

    /**
     *优惠列表(可选)
     *
     * Generated from protobuf field <code>repeated .proto.OtherAmount discount = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     *优惠列表(可选)
     *
     * Generated from protobuf field <code>repeated .proto.OtherAmount discount = 10;</code>
     * @param \Proto\OtherAmount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDiscount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\OtherAmount::class);
        $this->discount = $arr;

        return $this;
    }

    /**
     *其它费用列表(可选)
     *
     * Generated from protobuf field <code>repeated .proto.OtherAmount otherAmount = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOtherAmount()
    {
        return $this->otherAmount;
    }

    /**
     *其它费用列表(可选)
     *
     * Generated from protobuf field <code>repeated .proto.OtherAmount otherAmount = 11;</code>
     * @param \Proto\OtherAmount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOtherAmount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\OtherAmount::class);
        $this->otherAmount = $arr;

        return $this;
    }

    /**
     *预约时间，自提时间(可选)
     *
     * Generated from protobuf field <code>optional string orderBookTime = 12;</code>
     * @return string
     */
    public function getOrderBookTime()
    {
        return isset($this->orderBookTime) ? $this->orderBookTime : '';
    }

    public function hasOrderBookTime()
    {
        return isset($this->orderBookTime);
    }

    public function clearOrderBookTime()
    {
        unset($this->orderBookTime);
    }

    /**
     *预约时间，自提时间(可选)
     *
     * Generated from protobuf field <code>optional string orderBookTime = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderBookTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderBookTime = $var;

        return $this;
    }

    /**
     *订单备注(可选)
     *
     * Generated from protobuf field <code>optional string orderRemarks = 13;</code>
     * @return string
     */
    public function getOrderRemarks()
    {
        return isset($this->orderRemarks) ? $this->orderRemarks : '';
    }

    public function hasOrderRemarks()
    {
        return isset($this->orderRemarks);
    }

    public function clearOrderRemarks()
    {
        unset($this->orderRemarks);
    }

    /**
     *订单备注(可选)
     *
     * Generated from protobuf field <code>optional string orderRemarks = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderRemarks = $var;

        return $this;
    }

    /**
     *收货人姓名(可选)
     *
     * Generated from protobuf field <code>optional string toName = 14;</code>
     * @return string
     */
    public function getToName()
    {
        return isset($this->toName) ? $this->toName : '';
    }

    public function hasToName()
    {
        return isset($this->toName);
    }

    public function clearToName()
    {
        unset($this->toName);
    }

    /**
     *收货人姓名(可选)
     *
     * Generated from protobuf field <code>optional string toName = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setToName($var)
    {
        GPBUtil::checkString($var, True);
        $this->toName = $var;

        return $this;
    }

    /**
     *收货人地址(可选)
     *
     * Generated from protobuf field <code>optional string toAddress = 15;</code>
     * @return string
     */
    public function getToAddress()
    {
        return isset($this->toAddress) ? $this->toAddress : '';
    }

    public function hasToAddress()
    {
        return isset($this->toAddress);
    }

    public function clearToAddress()
    {
        unset($this->toAddress);
    }

    /**
     *收货人地址(可选)
     *
     * Generated from protobuf field <code>optional string toAddress = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setToAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->toAddress = $var;

        return $this;
    }

    /**
     *收货人电话(可选)
     *
     * Generated from protobuf field <code>optional string toMobile = 16;</code>
     * @return string
     */
    public function getToMobile()
    {
        return isset($this->toMobile) ? $this->toMobile : '';
    }

    public function hasToMobile()
    {
        return isset($this->toMobile);
    }

    public function clearToMobile()
    {
        unset($this->toMobile);
    }

    /**
     *收货人电话(可选)
     *
     * Generated from protobuf field <code>optional string toMobile = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setToMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->toMobile = $var;

        return $this;
    }

    /**
     *二维码显地址(可选)
     *
     * Generated from protobuf field <code>optional string qrCodeUrl = 17;</code>
     * @return string
     */
    public function getQrCodeUrl()
    {
        return isset($this->qrCodeUrl) ? $this->qrCodeUrl : '';
    }

    public function hasQrCodeUrl()
    {
        return isset($this->qrCodeUrl);
    }

    public function clearQrCodeUrl()
    {
        unset($this->qrCodeUrl);
    }

    /**
     *二维码显地址(可选)
     *
     * Generated from protobuf field <code>optional string qrCodeUrl = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setQrCodeUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->qrCodeUrl = $var;

        return $this;
    }

}

