<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/oss.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * OSS资源访问URL
 *
 * Generated from protobuf message <code>proto.OSSFileUrlResponse</code>
 */
class OSSFileUrlResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *OSS资源访问URL
     *
     * Generated from protobuf field <code>string ossUrl = 1;</code>
     */
    protected $ossUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ossUrl
     *          OSS资源访问URL
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Oss::initOnce();
        parent::__construct($data);
    }

    /**
     *OSS资源访问URL
     *
     * Generated from protobuf field <code>string ossUrl = 1;</code>
     * @return string
     */
    public function getOssUrl()
    {
        return $this->ossUrl;
    }

    /**
     *OSS资源访问URL
     *
     * Generated from protobuf field <code>string ossUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOssUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->ossUrl = $var;

        return $this;
    }

}

