<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/oss.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *OSS服务端签名返回参数
 *
 * Generated from protobuf message <code>proto.OSSPolicyTokenReturn</code>
 */
class OSSPolicyTokenReturn extends \Google\Protobuf\Internal\Message
{
    /**
     *AccessKeyId
     *
     * Generated from protobuf field <code>string accessid = 1;</code>
     */
    protected $accessid = '';
    /**
     *Endpoint
     *
     * Generated from protobuf field <code>string host = 2;</code>
     */
    protected $host = '';
    /**
     *有效时间
     *
     * Generated from protobuf field <code>int64 expire = 3;</code>
     */
    protected $expire = 0;
    /**
     *签名
     *
     * Generated from protobuf field <code>string signature = 4;</code>
     */
    protected $signature = '';
    /**
     *策略
     *
     * Generated from protobuf field <code>string policy = 5;</code>
     */
    protected $policy = '';
    /**
     *上传到OSS文件的前缀
     *
     * Generated from protobuf field <code>string dir = 6;</code>
     */
    protected $dir = '';
    /**
     *callbackUrl为上传回调服务器的URL（base64）
     *
     * Generated from protobuf field <code>string callback = 7;</code>
     */
    protected $callback = '';
    /**
     *新加，显示回调地下
     *
     * Generated from protobuf field <code>string callbackurl = 8;</code>
     */
    protected $callbackurl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $accessid
     *          AccessKeyId
     *     @type string $host
     *          Endpoint
     *     @type int|string $expire
     *          有效时间
     *     @type string $signature
     *          签名
     *     @type string $policy
     *          策略
     *     @type string $dir
     *          上传到OSS文件的前缀
     *     @type string $callback
     *          callbackUrl为上传回调服务器的URL（base64）
     *     @type string $callbackurl
     *          新加，显示回调地下
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Oss::initOnce();
        parent::__construct($data);
    }

    /**
     *AccessKeyId
     *
     * Generated from protobuf field <code>string accessid = 1;</code>
     * @return string
     */
    public function getAccessid()
    {
        return $this->accessid;
    }

    /**
     *AccessKeyId
     *
     * Generated from protobuf field <code>string accessid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessid($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessid = $var;

        return $this;
    }

    /**
     *Endpoint
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     *Endpoint
     *
     * Generated from protobuf field <code>string host = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     *有效时间
     *
     * Generated from protobuf field <code>int64 expire = 3;</code>
     * @return int|string
     */
    public function getExpire()
    {
        return $this->expire;
    }

    /**
     *有效时间
     *
     * Generated from protobuf field <code>int64 expire = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpire($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire = $var;

        return $this;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string signature = 4;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string signature = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

    /**
     *策略
     *
     * Generated from protobuf field <code>string policy = 5;</code>
     * @return string
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    /**
     *策略
     *
     * Generated from protobuf field <code>string policy = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPolicy($var)
    {
        GPBUtil::checkString($var, True);
        $this->policy = $var;

        return $this;
    }

    /**
     *上传到OSS文件的前缀
     *
     * Generated from protobuf field <code>string dir = 6;</code>
     * @return string
     */
    public function getDir()
    {
        return $this->dir;
    }

    /**
     *上传到OSS文件的前缀
     *
     * Generated from protobuf field <code>string dir = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDir($var)
    {
        GPBUtil::checkString($var, True);
        $this->dir = $var;

        return $this;
    }

    /**
     *callbackUrl为上传回调服务器的URL（base64）
     *
     * Generated from protobuf field <code>string callback = 7;</code>
     * @return string
     */
    public function getCallback()
    {
        return $this->callback;
    }

    /**
     *callbackUrl为上传回调服务器的URL（base64）
     *
     * Generated from protobuf field <code>string callback = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCallback($var)
    {
        GPBUtil::checkString($var, True);
        $this->callback = $var;

        return $this;
    }

    /**
     *新加，显示回调地下
     *
     * Generated from protobuf field <code>string callbackurl = 8;</code>
     * @return string
     */
    public function getCallbackurl()
    {
        return $this->callbackurl;
    }

    /**
     *新加，显示回调地下
     *
     * Generated from protobuf field <code>string callbackurl = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCallbackurl($var)
    {
        GPBUtil::checkString($var, True);
        $this->callbackurl = $var;

        return $this;
    }

}

