<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/oss.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *OSS上传Byte数组
 *
 * Generated from protobuf message <code>proto.OSSUploadByteParam</code>
 */
class OSSUploadByteParam extends \Google\Protobuf\Internal\Message
{
    /**
     *保存到OSS全路径
     *
     * Generated from protobuf field <code>string saveFileName = 1;</code>
     */
    protected $saveFileName = '';
    /**
     *文件byte
     *
     * Generated from protobuf field <code>bytes file = 2;</code>
     */
    protected $file = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $saveFileName
     *          保存到OSS全路径
     *     @type string $file
     *          文件byte
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Oss::initOnce();
        parent::__construct($data);
    }

    /**
     *保存到OSS全路径
     *
     * Generated from protobuf field <code>string saveFileName = 1;</code>
     * @return string
     */
    public function getSaveFileName()
    {
        return $this->saveFileName;
    }

    /**
     *保存到OSS全路径
     *
     * Generated from protobuf field <code>string saveFileName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSaveFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->saveFileName = $var;

        return $this;
    }

    /**
     *文件byte
     *
     * Generated from protobuf field <code>bytes file = 2;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     *文件byte
     *
     * Generated from protobuf field <code>bytes file = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, False);
        $this->file = $var;

        return $this;
    }

}

