<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mqtt.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.OtherAmount</code>
 */
class OtherAmount extends \Google\Protobuf\Internal\Message
{
    /**
     *名称
     *
     * Generated from protobuf field <code>optional string name = 1;</code>
     */
    protected $name = null;
    /**
     *金额
     *
     * Generated from protobuf field <code>optional string amount = 2;</code>
     */
    protected $amount = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          名称
     *     @type string $amount
     *          金额
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Mqtt::initOnce();
        parent::__construct($data);
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>optional string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>optional string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *金额
     *
     * Generated from protobuf field <code>optional string amount = 2;</code>
     * @return string
     */
    public function getAmount()
    {
        return isset($this->amount) ? $this->amount : '';
    }

    public function hasAmount()
    {
        return isset($this->amount);
    }

    public function clearAmount()
    {
        unset($this->amount);
    }

    /**
     *金额
     *
     * Generated from protobuf field <code>optional string amount = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

}

