<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pay.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *PayReturn JsApi及H5支付、扫码支付，返回参数
 *
 * Generated from protobuf message <code>proto.PayReturn</code>
 */
class PayReturn extends \Google\Protobuf\Internal\Message
{
    /**
     *支付方式
     *
     * Generated from protobuf field <code>.proto.PayMethod payMethod = 1;</code>
     */
    protected $payMethod = 0;
    /**
     *应用id
     *
     * Generated from protobuf field <code>string appId = 2;</code>
     */
    protected $appId = '';
    /**
     *微信支返回参数
     *
     * Generated from protobuf field <code>optional .proto.WxPayReturn wxPay = 3;</code>
     */
    protected $wxPay = null;
    /**
     *支付宝支付
     *
     * Generated from protobuf field <code>optional .proto.AliPayReturn aliPay = 4;</code>
     */
    protected $aliPay = null;
    /**
     *余额支付
     *
     * Generated from protobuf field <code>optional .proto.QihuiPayReturn qihuiPay = 5;</code>
     */
    protected $qihuiPay = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payMethod
     *          支付方式
     *     @type string $appId
     *          应用id
     *     @type \Proto\WxPayReturn $wxPay
     *          微信支返回参数
     *     @type \Proto\AliPayReturn $aliPay
     *          支付宝支付
     *     @type \Proto\QihuiPayReturn $qihuiPay
     *          余额支付
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     *支付方式
     *
     * Generated from protobuf field <code>.proto.PayMethod payMethod = 1;</code>
     * @return int
     */
    public function getPayMethod()
    {
        return $this->payMethod;
    }

    /**
     *支付方式
     *
     * Generated from protobuf field <code>.proto.PayMethod payMethod = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayMethod($var)
    {
        GPBUtil::checkEnum($var, \Proto\PayMethod::class);
        $this->payMethod = $var;

        return $this;
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string appId = 2;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     *应用id
     *
     * Generated from protobuf field <code>string appId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

    /**
     *微信支返回参数
     *
     * Generated from protobuf field <code>optional .proto.WxPayReturn wxPay = 3;</code>
     * @return \Proto\WxPayReturn|null
     */
    public function getWxPay()
    {
        return $this->wxPay;
    }

    public function hasWxPay()
    {
        return isset($this->wxPay);
    }

    public function clearWxPay()
    {
        unset($this->wxPay);
    }

    /**
     *微信支返回参数
     *
     * Generated from protobuf field <code>optional .proto.WxPayReturn wxPay = 3;</code>
     * @param \Proto\WxPayReturn $var
     * @return $this
     */
    public function setWxPay($var)
    {
        GPBUtil::checkMessage($var, \Proto\WxPayReturn::class);
        $this->wxPay = $var;

        return $this;
    }

    /**
     *支付宝支付
     *
     * Generated from protobuf field <code>optional .proto.AliPayReturn aliPay = 4;</code>
     * @return \Proto\AliPayReturn|null
     */
    public function getAliPay()
    {
        return $this->aliPay;
    }

    public function hasAliPay()
    {
        return isset($this->aliPay);
    }

    public function clearAliPay()
    {
        unset($this->aliPay);
    }

    /**
     *支付宝支付
     *
     * Generated from protobuf field <code>optional .proto.AliPayReturn aliPay = 4;</code>
     * @param \Proto\AliPayReturn $var
     * @return $this
     */
    public function setAliPay($var)
    {
        GPBUtil::checkMessage($var, \Proto\AliPayReturn::class);
        $this->aliPay = $var;

        return $this;
    }

    /**
     *余额支付
     *
     * Generated from protobuf field <code>optional .proto.QihuiPayReturn qihuiPay = 5;</code>
     * @return \Proto\QihuiPayReturn|null
     */
    public function getQihuiPay()
    {
        return $this->qihuiPay;
    }

    public function hasQihuiPay()
    {
        return isset($this->qihuiPay);
    }

    public function clearQihuiPay()
    {
        unset($this->qihuiPay);
    }

    /**
     *余额支付
     *
     * Generated from protobuf field <code>optional .proto.QihuiPayReturn qihuiPay = 5;</code>
     * @param \Proto\QihuiPayReturn $var
     * @return $this
     */
    public function setQihuiPay($var)
    {
        GPBUtil::checkMessage($var, \Proto\QihuiPayReturn::class);
        $this->qihuiPay = $var;

        return $this;
    }

}

