<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mqtt.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PrintGoods</code>
 */
class PrintGoods extends \Google\Protobuf\Internal\Message
{
    /**
     *商品标题
     *
     * Generated from protobuf field <code>string goodsTitle = 1;</code>
     */
    protected $goodsTitle = '';
    /**
     *商品规格标题
     *
     * Generated from protobuf field <code>optional string goodsSpecTitle = 2;</code>
     */
    protected $goodsSpecTitle = null;
    /**
     *数量
     *
     * Generated from protobuf field <code>string total = 3;</code>
     */
    protected $total = '';
    /**
     *价格（单位元）
     *
     * Generated from protobuf field <code>string amount = 4;</code>
     */
    protected $amount = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $goodsTitle
     *          商品标题
     *     @type string $goodsSpecTitle
     *          商品规格标题
     *     @type string $total
     *          数量
     *     @type string $amount
     *          价格（单位元）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Mqtt::initOnce();
        parent::__construct($data);
    }

    /**
     *商品标题
     *
     * Generated from protobuf field <code>string goodsTitle = 1;</code>
     * @return string
     */
    public function getGoodsTitle()
    {
        return $this->goodsTitle;
    }

    /**
     *商品标题
     *
     * Generated from protobuf field <code>string goodsTitle = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGoodsTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->goodsTitle = $var;

        return $this;
    }

    /**
     *商品规格标题
     *
     * Generated from protobuf field <code>optional string goodsSpecTitle = 2;</code>
     * @return string
     */
    public function getGoodsSpecTitle()
    {
        return isset($this->goodsSpecTitle) ? $this->goodsSpecTitle : '';
    }

    public function hasGoodsSpecTitle()
    {
        return isset($this->goodsSpecTitle);
    }

    public function clearGoodsSpecTitle()
    {
        unset($this->goodsSpecTitle);
    }

    /**
     *商品规格标题
     *
     * Generated from protobuf field <code>optional string goodsSpecTitle = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGoodsSpecTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->goodsSpecTitle = $var;

        return $this;
    }

    /**
     *数量
     *
     * Generated from protobuf field <code>string total = 3;</code>
     * @return string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     *数量
     *
     * Generated from protobuf field <code>string total = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->total = $var;

        return $this;
    }

    /**
     *价格（单位元）
     *
     * Generated from protobuf field <code>string amount = 4;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *价格（单位元）
     *
     * Generated from protobuf field <code>string amount = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

}

