<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pay.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.QueryOrderParam</code>
 */
class QueryOrderParam extends \Google\Protobuf\Internal\Message
{
    /**
     *平台订单号
     *
     * Generated from protobuf field <code>string oid = 1;</code>
     */
    protected $oid = '';
    /**
     *APPID
     *
     * Generated from protobuf field <code>optional string appid = 2;</code>
     */
    protected $appid = null;
    /**
     *支付方式
     *
     * Generated from protobuf field <code>optional .proto.PayMethod payMethod = 3;</code>
     */
    protected $payMethod = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $oid
     *          平台订单号
     *     @type string $appid
     *          APPID
     *     @type int $payMethod
     *          支付方式
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     *平台订单号
     *
     * Generated from protobuf field <code>string oid = 1;</code>
     * @return string
     */
    public function getOid()
    {
        return $this->oid;
    }

    /**
     *平台订单号
     *
     * Generated from protobuf field <code>string oid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOid($var)
    {
        GPBUtil::checkString($var, True);
        $this->oid = $var;

        return $this;
    }

    /**
     *APPID
     *
     * Generated from protobuf field <code>optional string appid = 2;</code>
     * @return string
     */
    public function getAppid()
    {
        return isset($this->appid) ? $this->appid : '';
    }

    public function hasAppid()
    {
        return isset($this->appid);
    }

    public function clearAppid()
    {
        unset($this->appid);
    }

    /**
     *APPID
     *
     * Generated from protobuf field <code>optional string appid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppid($var)
    {
        GPBUtil::checkString($var, True);
        $this->appid = $var;

        return $this;
    }

    /**
     *支付方式
     *
     * Generated from protobuf field <code>optional .proto.PayMethod payMethod = 3;</code>
     * @return int
     */
    public function getPayMethod()
    {
        return isset($this->payMethod) ? $this->payMethod : 0;
    }

    public function hasPayMethod()
    {
        return isset($this->payMethod);
    }

    public function clearPayMethod()
    {
        unset($this->payMethod);
    }

    /**
     *支付方式
     *
     * Generated from protobuf field <code>optional .proto.PayMethod payMethod = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPayMethod($var)
    {
        GPBUtil::checkEnum($var, \Proto\PayMethod::class);
        $this->payMethod = $var;

        return $this;
    }

}

