<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pay.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.QueryOrderRetrun</code>
 */
class QueryOrderRetrun extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string appId = 1;</code>
     */
    protected $appId = '';
    /**
     *平台订单号
     *
     * Generated from protobuf field <code>string oid = 2;</code>
     */
    protected $oid = '';
    /**
     *当前系统订单号（base订单）
     *
     * Generated from protobuf field <code>string baseOrderId = 3;</code>
     */
    protected $baseOrderId = '';
    /**
     *支付平台交易号
     *
     * Generated from protobuf field <code>string tradeNo = 4;</code>
     */
    protected $tradeNo = '';
    /**
     *交易类型
     *
     * Generated from protobuf field <code>string tradeType = 5;</code>
     */
    protected $tradeType = '';
    /**
     *交易状态 SUCCESS：支付成功 REFUND：转入退款 NOTPAY：未支付 CLOSED：已关闭 REVOKED：已撤销（付款码支付） USERPAYING：用户支付中（付款码支付） PAYERROR：支付失败(其他原因，如银行返回失败) ACCEPT：已接收，等待扣款
     *
     * Generated from protobuf field <code>string tradeState = 6;</code>
     */
    protected $tradeState = '';
    /**
     *支付时间
     *
     * Generated from protobuf field <code>string payTime = 7;</code>
     */
    protected $payTime = '';
    /**
     *支付金额（分）
     *
     * Generated from protobuf field <code>int32 payAmount = 8;</code>
     */
    protected $payAmount = 0;
    /**
     *支付方式
     *
     * Generated from protobuf field <code>.proto.PayMethod payMethod = 9;</code>
     */
    protected $payMethod = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appId
     *     @type string $oid
     *          平台订单号
     *     @type string $baseOrderId
     *          当前系统订单号（base订单）
     *     @type string $tradeNo
     *          支付平台交易号
     *     @type string $tradeType
     *          交易类型
     *     @type string $tradeState
     *          交易状态 SUCCESS：支付成功 REFUND：转入退款 NOTPAY：未支付 CLOSED：已关闭 REVOKED：已撤销（付款码支付） USERPAYING：用户支付中（付款码支付） PAYERROR：支付失败(其他原因，如银行返回失败) ACCEPT：已接收，等待扣款
     *     @type string $payTime
     *          支付时间
     *     @type int $payAmount
     *          支付金额（分）
     *     @type int $payMethod
     *          支付方式
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string appId = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * Generated from protobuf field <code>string appId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

    /**
     *平台订单号
     *
     * Generated from protobuf field <code>string oid = 2;</code>
     * @return string
     */
    public function getOid()
    {
        return $this->oid;
    }

    /**
     *平台订单号
     *
     * Generated from protobuf field <code>string oid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOid($var)
    {
        GPBUtil::checkString($var, True);
        $this->oid = $var;

        return $this;
    }

    /**
     *当前系统订单号（base订单）
     *
     * Generated from protobuf field <code>string baseOrderId = 3;</code>
     * @return string
     */
    public function getBaseOrderId()
    {
        return $this->baseOrderId;
    }

    /**
     *当前系统订单号（base订单）
     *
     * Generated from protobuf field <code>string baseOrderId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->baseOrderId = $var;

        return $this;
    }

    /**
     *支付平台交易号
     *
     * Generated from protobuf field <code>string tradeNo = 4;</code>
     * @return string
     */
    public function getTradeNo()
    {
        return $this->tradeNo;
    }

    /**
     *支付平台交易号
     *
     * Generated from protobuf field <code>string tradeNo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tradeNo = $var;

        return $this;
    }

    /**
     *交易类型
     *
     * Generated from protobuf field <code>string tradeType = 5;</code>
     * @return string
     */
    public function getTradeType()
    {
        return $this->tradeType;
    }

    /**
     *交易类型
     *
     * Generated from protobuf field <code>string tradeType = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->tradeType = $var;

        return $this;
    }

    /**
     *交易状态 SUCCESS：支付成功 REFUND：转入退款 NOTPAY：未支付 CLOSED：已关闭 REVOKED：已撤销（付款码支付） USERPAYING：用户支付中（付款码支付） PAYERROR：支付失败(其他原因，如银行返回失败) ACCEPT：已接收，等待扣款
     *
     * Generated from protobuf field <code>string tradeState = 6;</code>
     * @return string
     */
    public function getTradeState()
    {
        return $this->tradeState;
    }

    /**
     *交易状态 SUCCESS：支付成功 REFUND：转入退款 NOTPAY：未支付 CLOSED：已关闭 REVOKED：已撤销（付款码支付） USERPAYING：用户支付中（付款码支付） PAYERROR：支付失败(其他原因，如银行返回失败) ACCEPT：已接收，等待扣款
     *
     * Generated from protobuf field <code>string tradeState = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeState($var)
    {
        GPBUtil::checkString($var, True);
        $this->tradeState = $var;

        return $this;
    }

    /**
     *支付时间
     *
     * Generated from protobuf field <code>string payTime = 7;</code>
     * @return string
     */
    public function getPayTime()
    {
        return $this->payTime;
    }

    /**
     *支付时间
     *
     * Generated from protobuf field <code>string payTime = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPayTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->payTime = $var;

        return $this;
    }

    /**
     *支付金额（分）
     *
     * Generated from protobuf field <code>int32 payAmount = 8;</code>
     * @return int
     */
    public function getPayAmount()
    {
        return $this->payAmount;
    }

    /**
     *支付金额（分）
     *
     * Generated from protobuf field <code>int32 payAmount = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPayAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->payAmount = $var;

        return $this;
    }

    /**
     *支付方式
     *
     * Generated from protobuf field <code>.proto.PayMethod payMethod = 9;</code>
     * @return int
     */
    public function getPayMethod()
    {
        return $this->payMethod;
    }

    /**
     *支付方式
     *
     * Generated from protobuf field <code>.proto.PayMethod payMethod = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPayMethod($var)
    {
        GPBUtil::checkEnum($var, \Proto\PayMethod::class);
        $this->payMethod = $var;

        return $this;
    }

}

