<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ocr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *识别身份信息
 *
 * Generated from protobuf message <code>proto.RecognizeIdentityCardResponse</code>
 */
class RecognizeIdentityCardResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *身份证正面
     *
     * Generated from protobuf field <code>optional .proto.IdentityCardFace face = 1;</code>
     */
    protected $face = null;
    /**
     *身份反面
     *
     * Generated from protobuf field <code>optional .proto.IdentityCardBack back = 2;</code>
     */
    protected $back = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\IdentityCardFace $face
     *          身份证正面
     *     @type \Proto\IdentityCardBack $back
     *          身份反面
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     *身份证正面
     *
     * Generated from protobuf field <code>optional .proto.IdentityCardFace face = 1;</code>
     * @return \Proto\IdentityCardFace|null
     */
    public function getFace()
    {
        return $this->face;
    }

    public function hasFace()
    {
        return isset($this->face);
    }

    public function clearFace()
    {
        unset($this->face);
    }

    /**
     *身份证正面
     *
     * Generated from protobuf field <code>optional .proto.IdentityCardFace face = 1;</code>
     * @param \Proto\IdentityCardFace $var
     * @return $this
     */
    public function setFace($var)
    {
        GPBUtil::checkMessage($var, \Proto\IdentityCardFace::class);
        $this->face = $var;

        return $this;
    }

    /**
     *身份反面
     *
     * Generated from protobuf field <code>optional .proto.IdentityCardBack back = 2;</code>
     * @return \Proto\IdentityCardBack|null
     */
    public function getBack()
    {
        return $this->back;
    }

    public function hasBack()
    {
        return isset($this->back);
    }

    public function clearBack()
    {
        unset($this->back);
    }

    /**
     *身份反面
     *
     * Generated from protobuf field <code>optional .proto.IdentityCardBack back = 2;</code>
     * @param \Proto\IdentityCardBack $var
     * @return $this
     */
    public function setBack($var)
    {
        GPBUtil::checkMessage($var, \Proto\IdentityCardBack::class);
        $this->back = $var;

        return $this;
    }

}

