<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ocr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RecognizeIdentityCardParam</code>
 */
class RecognizeIdentityCardParam extends \Google\Protobuf\Internal\Message
{
    /**
     *身份证正反面，face 正面，back 反面
     *
     * Generated from protobuf field <code>string side = 1;</code>
     */
    protected $side = '';
    /**
     *身份证OSS保存地址字符串
     *
     * Generated from protobuf field <code>string photoUrl = 2;</code>
     */
    protected $photoUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $side
     *          身份证正反面，face 正面，back 反面
     *     @type string $photoUrl
     *          身份证OSS保存地址字符串
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     *身份证正反面，face 正面，back 反面
     *
     * Generated from protobuf field <code>string side = 1;</code>
     * @return string
     */
    public function getSide()
    {
        return $this->side;
    }

    /**
     *身份证正反面，face 正面，back 反面
     *
     * Generated from protobuf field <code>string side = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSide($var)
    {
        GPBUtil::checkString($var, True);
        $this->side = $var;

        return $this;
    }

    /**
     *身份证OSS保存地址字符串
     *
     * Generated from protobuf field <code>string photoUrl = 2;</code>
     * @return string
     */
    public function getPhotoUrl()
    {
        return $this->photoUrl;
    }

    /**
     *身份证OSS保存地址字符串
     *
     * Generated from protobuf field <code>string photoUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->photoUrl = $var;

        return $this;
    }

}

