<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ocr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *营业执照信息识别
 *
 * Generated from protobuf message <code>proto.RecognizeBusinessLicenseResponse</code>
 */
class RecognizeBusinessLicenseResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *公司类型
     *
     * Generated from protobuf field <code>optional string type = 1;</code>
     */
    protected $type = null;
    /**
     *公司注册日期
     *
     * Generated from protobuf field <code>optional string establishDate = 2;</code>
     */
    protected $establishDate = null;
    /**
     *公司营业期限终止日期
     *
     * Generated from protobuf field <code>optional string validPeriod = 3;</code>
     */
    protected $validPeriod = null;
    /**
     *经营范围
     *
     * Generated from protobuf field <code>optional string business = 4;</code>
     */
    protected $business = null;
    /**
     *输入图片的角度（顺时针旋转）
     *
     * Generated from protobuf field <code>optional float angle = 5;</code>
     */
    protected $angle = null;
    /**
     *统一社会信用代码
     *
     * Generated from protobuf field <code>optional string registerNumber = 6;</code>
     */
    protected $registerNumber = null;
    /**
     *公司地址
     *
     * Generated from protobuf field <code>optional string address = 7;</code>
     */
    protected $address = null;
    /**
     *注册资本
     *
     * Generated from protobuf field <code>optional string capital = 8;</code>
     */
    protected $capital = null;
    /**
     *公司名称
     *
     * Generated from protobuf field <code>optional string name = 9;</code>
     */
    protected $name = null;
    /**
     *公司法人
     *
     * Generated from protobuf field <code>optional string legalPerson = 10;</code>
     */
    protected $legalPerson = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *          公司类型
     *     @type string $establishDate
     *          公司注册日期
     *     @type string $validPeriod
     *          公司营业期限终止日期
     *     @type string $business
     *          经营范围
     *     @type float $angle
     *          输入图片的角度（顺时针旋转）
     *     @type string $registerNumber
     *          统一社会信用代码
     *     @type string $address
     *          公司地址
     *     @type string $capital
     *          注册资本
     *     @type string $name
     *          公司名称
     *     @type string $legalPerson
     *          公司法人
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     *公司类型
     *
     * Generated from protobuf field <code>optional string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : '';
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     *公司类型
     *
     * Generated from protobuf field <code>optional string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     *公司注册日期
     *
     * Generated from protobuf field <code>optional string establishDate = 2;</code>
     * @return string
     */
    public function getEstablishDate()
    {
        return isset($this->establishDate) ? $this->establishDate : '';
    }

    public function hasEstablishDate()
    {
        return isset($this->establishDate);
    }

    public function clearEstablishDate()
    {
        unset($this->establishDate);
    }

    /**
     *公司注册日期
     *
     * Generated from protobuf field <code>optional string establishDate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEstablishDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->establishDate = $var;

        return $this;
    }

    /**
     *公司营业期限终止日期
     *
     * Generated from protobuf field <code>optional string validPeriod = 3;</code>
     * @return string
     */
    public function getValidPeriod()
    {
        return isset($this->validPeriod) ? $this->validPeriod : '';
    }

    public function hasValidPeriod()
    {
        return isset($this->validPeriod);
    }

    public function clearValidPeriod()
    {
        unset($this->validPeriod);
    }

    /**
     *公司营业期限终止日期
     *
     * Generated from protobuf field <code>optional string validPeriod = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValidPeriod($var)
    {
        GPBUtil::checkString($var, True);
        $this->validPeriod = $var;

        return $this;
    }

    /**
     *经营范围
     *
     * Generated from protobuf field <code>optional string business = 4;</code>
     * @return string
     */
    public function getBusiness()
    {
        return isset($this->business) ? $this->business : '';
    }

    public function hasBusiness()
    {
        return isset($this->business);
    }

    public function clearBusiness()
    {
        unset($this->business);
    }

    /**
     *经营范围
     *
     * Generated from protobuf field <code>optional string business = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBusiness($var)
    {
        GPBUtil::checkString($var, True);
        $this->business = $var;

        return $this;
    }

    /**
     *输入图片的角度（顺时针旋转）
     *
     * Generated from protobuf field <code>optional float angle = 5;</code>
     * @return float
     */
    public function getAngle()
    {
        return isset($this->angle) ? $this->angle : 0.0;
    }

    public function hasAngle()
    {
        return isset($this->angle);
    }

    public function clearAngle()
    {
        unset($this->angle);
    }

    /**
     *输入图片的角度（顺时针旋转）
     *
     * Generated from protobuf field <code>optional float angle = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setAngle($var)
    {
        GPBUtil::checkFloat($var);
        $this->angle = $var;

        return $this;
    }

    /**
     *统一社会信用代码
     *
     * Generated from protobuf field <code>optional string registerNumber = 6;</code>
     * @return string
     */
    public function getRegisterNumber()
    {
        return isset($this->registerNumber) ? $this->registerNumber : '';
    }

    public function hasRegisterNumber()
    {
        return isset($this->registerNumber);
    }

    public function clearRegisterNumber()
    {
        unset($this->registerNumber);
    }

    /**
     *统一社会信用代码
     *
     * Generated from protobuf field <code>optional string registerNumber = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRegisterNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->registerNumber = $var;

        return $this;
    }

    /**
     *公司地址
     *
     * Generated from protobuf field <code>optional string address = 7;</code>
     * @return string
     */
    public function getAddress()
    {
        return isset($this->address) ? $this->address : '';
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     *公司地址
     *
     * Generated from protobuf field <code>optional string address = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     *注册资本
     *
     * Generated from protobuf field <code>optional string capital = 8;</code>
     * @return string
     */
    public function getCapital()
    {
        return isset($this->capital) ? $this->capital : '';
    }

    public function hasCapital()
    {
        return isset($this->capital);
    }

    public function clearCapital()
    {
        unset($this->capital);
    }

    /**
     *注册资本
     *
     * Generated from protobuf field <code>optional string capital = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCapital($var)
    {
        GPBUtil::checkString($var, True);
        $this->capital = $var;

        return $this;
    }

    /**
     *公司名称
     *
     * Generated from protobuf field <code>optional string name = 9;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     *公司名称
     *
     * Generated from protobuf field <code>optional string name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *公司法人
     *
     * Generated from protobuf field <code>optional string legalPerson = 10;</code>
     * @return string
     */
    public function getLegalPerson()
    {
        return isset($this->legalPerson) ? $this->legalPerson : '';
    }

    public function hasLegalPerson()
    {
        return isset($this->legalPerson);
    }

    public function clearLegalPerson()
    {
        unset($this->legalPerson);
    }

    /**
     *公司法人
     *
     * Generated from protobuf field <code>optional string legalPerson = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLegalPerson($var)
    {
        GPBUtil::checkString($var, True);
        $this->legalPerson = $var;

        return $this;
    }

}

