<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/nls.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RecognizeSpeechResponse</code>
 */
class RecognizeSpeechResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *服务状态描述
     *
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';
    /**
     *语音识别结果
     *
     * Generated from protobuf field <code>string result = 2;</code>
     */
    protected $result = '';
    /**
     *服务状态码
     *
     * Generated from protobuf field <code>int32 status = 3;</code>
     */
    protected $status = 0;
    /**
     *32位任务ID。请您记录该值，以便排查错误
     *
     * Generated from protobuf field <code>string taskId = 4;</code>
     */
    protected $taskId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *          服务状态描述
     *     @type string $result
     *          语音识别结果
     *     @type int $status
     *          服务状态码
     *     @type string $taskId
     *          32位任务ID。请您记录该值，以便排查错误
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Nls::initOnce();
        parent::__construct($data);
    }

    /**
     *服务状态描述
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     *服务状态描述
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     *语音识别结果
     *
     * Generated from protobuf field <code>string result = 2;</code>
     * @return string
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     *语音识别结果
     *
     * Generated from protobuf field <code>string result = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->result = $var;

        return $this;
    }

    /**
     *服务状态码
     *
     * Generated from protobuf field <code>int32 status = 3;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *服务状态码
     *
     * Generated from protobuf field <code>int32 status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     *32位任务ID。请您记录该值，以便排查错误
     *
     * Generated from protobuf field <code>string taskId = 4;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->taskId;
    }

    /**
     *32位任务ID。请您记录该值，以便排查错误
     *
     * Generated from protobuf field <code>string taskId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->taskId = $var;

        return $this;
    }

}

