<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ocr.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RecognizeBusinessLicenseParam</code>
 */
class RecognizeBusinessLicenseParam extends \Google\Protobuf\Internal\Message
{
    /**
     *营业执照地址
     *
     * Generated from protobuf field <code>string photoUrl = 1;</code>
     */
    protected $photoUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $photoUrl
     *          营业执照地址
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     *营业执照地址
     *
     * Generated from protobuf field <code>string photoUrl = 1;</code>
     * @return string
     */
    public function getPhotoUrl()
    {
        return $this->photoUrl;
    }

    /**
     *营业执照地址
     *
     * Generated from protobuf field <code>string photoUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->photoUrl = $var;

        return $this;
    }

}

