<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/base.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ResultMessage</code>
 */
class ResultMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *返回代码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     *返回信息
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    protected $msg = '';
    /**
     *消息体
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 3;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *          返回代码
     *     @type string $msg
     *          返回信息
     *     @type \Google\Protobuf\Any $data
     *          消息体
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Base::initOnce();
        parent::__construct($data);
    }

    /**
     *返回代码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *返回代码
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     *返回信息
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     *返回信息
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     *消息体
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 3;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     *消息体
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 3;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->data = $var;

        return $this;
    }

}

