<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sms.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *短信服务返回结果
 *
 * Generated from protobuf message <code>proto.SendSmsResponse</code>
 */
class SendSmsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *请求ID
     *
     * Generated from protobuf field <code>string RequestId = 1;</code>
     */
    protected $RequestId = '';
    /**
     *状态码的描述。
     *
     * Generated from protobuf field <code>string Message = 2;</code>
     */
    protected $Message = '';
    /**
     *发送回执ID
     *
     * Generated from protobuf field <code>string BizId = 3;</code>
     */
    protected $BizId = '';
    /**
     *请求状态码，返回OK代表请求成功
     *
     * Generated from protobuf field <code>string Code = 4;</code>
     */
    protected $Code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RequestId
     *          请求ID
     *     @type string $Message
     *          状态码的描述。
     *     @type string $BizId
     *          发送回执ID
     *     @type string $Code
     *          请求状态码，返回OK代表请求成功
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Sms::initOnce();
        parent::__construct($data);
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string RequestId = 1;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->RequestId;
    }

    /**
     *请求ID
     *
     * Generated from protobuf field <code>string RequestId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestId = $var;

        return $this;
    }

    /**
     *状态码的描述。
     *
     * Generated from protobuf field <code>string Message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     *状态码的描述。
     *
     * Generated from protobuf field <code>string Message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

    /**
     *发送回执ID
     *
     * Generated from protobuf field <code>string BizId = 3;</code>
     * @return string
     */
    public function getBizId()
    {
        return $this->BizId;
    }

    /**
     *发送回执ID
     *
     * Generated from protobuf field <code>string BizId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBizId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BizId = $var;

        return $this;
    }

    /**
     *请求状态码，返回OK代表请求成功
     *
     * Generated from protobuf field <code>string Code = 4;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     *请求状态码，返回OK代表请求成功
     *
     * Generated from protobuf field <code>string Code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

}

