<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/upload.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UploadParam</code>
 */
class UploadParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Content = 1;</code>
     */
    protected $Content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Upload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Generated from protobuf field <code>bytes Content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

}

