<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 微信小程序解密后 用户手机号结构体
 *
 * Generated from protobuf message <code>proto.UserPhoneResponse</code>
 */
class UserPhoneResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string phoneNumber = 1;</code>
     */
    protected $phoneNumber = '';
    /**
     * Generated from protobuf field <code>string purePhoneNumber = 2;</code>
     */
    protected $purePhoneNumber = '';
    /**
     * Generated from protobuf field <code>string countryCode = 3;</code>
     */
    protected $countryCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phoneNumber
     *     @type string $purePhoneNumber
     *     @type string $countryCode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 1;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string purePhoneNumber = 2;</code>
     * @return string
     */
    public function getPurePhoneNumber()
    {
        return $this->purePhoneNumber;
    }

    /**
     * Generated from protobuf field <code>string purePhoneNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPurePhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->purePhoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string countryCode = 3;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->countryCode;
    }

    /**
     * Generated from protobuf field <code>string countryCode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->countryCode = $var;

        return $this;
    }

}

