<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sms.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *检查短信验证码
 *
 * Generated from protobuf message <code>proto.VerifyAuthSmsParam</code>
 */
class VerifyAuthSmsParam extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     */
    protected $phone = '';
    /**
     *短信验证码
     *
     * Generated from protobuf field <code>string smscode = 2;</code>
     */
    protected $smscode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phone
     *          手机号码
     *     @type string $smscode
     *          短信验证码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Sms::initOnce();
        parent::__construct($data);
    }

    /**
     *手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *手机号码
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     *短信验证码
     *
     * Generated from protobuf field <code>string smscode = 2;</code>
     * @return string
     */
    public function getSmscode()
    {
        return $this->smscode;
    }

    /**
     *短信验证码
     *
     * Generated from protobuf field <code>string smscode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSmscode($var)
    {
        GPBUtil::checkString($var, True);
        $this->smscode = $var;

        return $this;
    }

}

