<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sms.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *验证短信验证码结果
 *
 * Generated from protobuf message <code>proto.VerifAuthsms</code>
 */
class VerifAuthsms extends \Google\Protobuf\Internal\Message
{
    /**
     *验证码是否成功，成功返回true
     *
     * Generated from protobuf field <code>bool isSuccess = 1;</code>
     */
    protected $isSuccess = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isSuccess
     *          验证码是否成功，成功返回true
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Sms::initOnce();
        parent::__construct($data);
    }

    /**
     *验证码是否成功，成功返回true
     *
     * Generated from protobuf field <code>bool isSuccess = 1;</code>
     * @return bool
     */
    public function getIsSuccess()
    {
        return $this->isSuccess;
    }

    /**
     *验证码是否成功，成功返回true
     *
     * Generated from protobuf field <code>bool isSuccess = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->isSuccess = $var;

        return $this;
    }

}

