<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *微信通用入参 
 *
 * Generated from protobuf message <code>proto.WeChatBaseParam</code>
 */
class WeChatBaseParam extends \Google\Protobuf\Internal\Message
{
    /**
     *小程序的APPID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     */
    protected $appId = '';
    /**
     *
     * Generated from protobuf field <code>optional string accessToken = 2;</code>
     */
    protected $accessToken = null;
    /**
     *登录code
     *
     * Generated from protobuf field <code>optional string authCode = 3;</code>
     */
    protected $authCode = null;
    /**
     *用户名的openid，注意要和appid对应
     *
     * Generated from protobuf field <code>optional string openId = 4;</code>
     */
    protected $openId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appId
     *          小程序的APPID
     *     @type string $accessToken
     *     @type string $authCode
     *          登录code
     *     @type string $openId
     *          用户名的openid，注意要和appid对应
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     *小程序的APPID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     *小程序的APPID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

    /**
     *
     * Generated from protobuf field <code>optional string accessToken = 2;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return isset($this->accessToken) ? $this->accessToken : '';
    }

    public function hasAccessToken()
    {
        return isset($this->accessToken);
    }

    public function clearAccessToken()
    {
        unset($this->accessToken);
    }

    /**
     *
     * Generated from protobuf field <code>optional string accessToken = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessToken = $var;

        return $this;
    }

    /**
     *登录code
     *
     * Generated from protobuf field <code>optional string authCode = 3;</code>
     * @return string
     */
    public function getAuthCode()
    {
        return isset($this->authCode) ? $this->authCode : '';
    }

    public function hasAuthCode()
    {
        return isset($this->authCode);
    }

    public function clearAuthCode()
    {
        unset($this->authCode);
    }

    /**
     *登录code
     *
     * Generated from protobuf field <code>optional string authCode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->authCode = $var;

        return $this;
    }

    /**
     *用户名的openid，注意要和appid对应
     *
     * Generated from protobuf field <code>optional string openId = 4;</code>
     * @return string
     */
    public function getOpenId()
    {
        return isset($this->openId) ? $this->openId : '';
    }

    public function hasOpenId()
    {
        return isset($this->openId);
    }

    public function clearOpenId()
    {
        unset($this->openId);
    }

    /**
     *用户名的openid，注意要和appid对应
     *
     * Generated from protobuf field <code>optional string openId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->openId = $var;

        return $this;
    }

}

