<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *微信解密用户信息
 *
 * Generated from protobuf message <code>proto.WxDecryptUserInfoResponse</code>
 */
class WxDecryptUserInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *用户唯一标识
     *
     * Generated from protobuf field <code>string openId = 1;</code>
     */
    protected $openId = '';
    /**
     *用户昵称
     *
     * Generated from protobuf field <code>string nickName = 2;</code>
     */
    protected $nickName = '';
    /**
     *性别
     *
     * Generated from protobuf field <code>int32 gender = 3;</code>
     */
    protected $gender = 0;
    /**
     *城市
     *
     * Generated from protobuf field <code>string city = 4;</code>
     */
    protected $city = '';
    /**
     *省份
     *
     * Generated from protobuf field <code>string province = 5;</code>
     */
    protected $province = '';
    /**
     *国家
     *
     * Generated from protobuf field <code>string country = 6;</code>
     */
    protected $country = '';
    /**
     *头像
     *
     * Generated from protobuf field <code>string avatarUrl = 7;</code>
     */
    protected $avatarUrl = '';
    /**
     *用户在开放平台的唯一标识符
     *
     * Generated from protobuf field <code>string unionId = 8;</code>
     */
    protected $unionId = '';
    /**
     *水印
     *
     * Generated from protobuf field <code>.proto.Watermark watermark = 9;</code>
     */
    protected $watermark = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $openId
     *          用户唯一标识
     *     @type string $nickName
     *          用户昵称
     *     @type int $gender
     *          性别
     *     @type string $city
     *          城市
     *     @type string $province
     *          省份
     *     @type string $country
     *          国家
     *     @type string $avatarUrl
     *          头像
     *     @type string $unionId
     *          用户在开放平台的唯一标识符
     *     @type \Proto\Watermark $watermark
     *          水印
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     *用户唯一标识
     *
     * Generated from protobuf field <code>string openId = 1;</code>
     * @return string
     */
    public function getOpenId()
    {
        return $this->openId;
    }

    /**
     *用户唯一标识
     *
     * Generated from protobuf field <code>string openId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->openId = $var;

        return $this;
    }

    /**
     *用户昵称
     *
     * Generated from protobuf field <code>string nickName = 2;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->nickName;
    }

    /**
     *用户昵称
     *
     * Generated from protobuf field <code>string nickName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickName = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>int32 gender = 3;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>int32 gender = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->gender = $var;

        return $this;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string city = 4;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string city = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string province = 5;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string province = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->province = $var;

        return $this;
    }

    /**
     *国家
     *
     * Generated from protobuf field <code>string country = 6;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     *国家
     *
     * Generated from protobuf field <code>string country = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string avatarUrl = 7;</code>
     * @return string
     */
    public function getAvatarUrl()
    {
        return $this->avatarUrl;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string avatarUrl = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatarUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatarUrl = $var;

        return $this;
    }

    /**
     *用户在开放平台的唯一标识符
     *
     * Generated from protobuf field <code>string unionId = 8;</code>
     * @return string
     */
    public function getUnionId()
    {
        return $this->unionId;
    }

    /**
     *用户在开放平台的唯一标识符
     *
     * Generated from protobuf field <code>string unionId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->unionId = $var;

        return $this;
    }

    /**
     *水印
     *
     * Generated from protobuf field <code>.proto.Watermark watermark = 9;</code>
     * @return \Proto\Watermark|null
     */
    public function getWatermark()
    {
        return $this->watermark;
    }

    public function hasWatermark()
    {
        return isset($this->watermark);
    }

    public function clearWatermark()
    {
        unset($this->watermark);
    }

    /**
     *水印
     *
     * Generated from protobuf field <code>.proto.Watermark watermark = 9;</code>
     * @param \Proto\Watermark $var
     * @return $this
     */
    public function setWatermark($var)
    {
        GPBUtil::checkMessage($var, \Proto\Watermark::class);
        $this->watermark = $var;

        return $this;
    }

}

