<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *WxMiniPathParam 小程二维码入参
 *
 * Generated from protobuf message <code>proto.WxMiniPathParam</code>
 */
class WxMiniPathParam extends \Google\Protobuf\Internal\Message
{
    /**
     *小程序的APPID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     */
    protected $appId = '';
    /**
     *如果为path简单二维码时不能为空，最大长度 128 字节
     *
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     *二维码的宽度，单位 px，最小 280px，最大 1280px
     *
     * Generated from protobuf field <code>int32 width = 3;</code>
     */
    protected $width = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appId
     *          小程序的APPID
     *     @type string $path
     *          如果为path简单二维码时不能为空，最大长度 128 字节
     *     @type int $width
     *          二维码的宽度，单位 px，最小 280px，最大 1280px
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     *小程序的APPID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     *小程序的APPID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

    /**
     *如果为path简单二维码时不能为空，最大长度 128 字节
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     *如果为path简单二维码时不能为空，最大长度 128 字节
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     *二维码的宽度，单位 px，最小 280px，最大 1280px
     *
     * Generated from protobuf field <code>int32 width = 3;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     *二维码的宽度，单位 px，最小 280px，最大 1280px
     *
     * Generated from protobuf field <code>int32 width = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

}

