<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pay.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.WxPayReturn</code>
 */
class WxPayReturn extends \Google\Protobuf\Internal\Message
{
    /**
     *因为微信的其奇怪设计，有两个时戳，一个小驼峰，一个不是。系统只返回一个，需要自行格式
     *
     * Generated from protobuf field <code>string timeStamp = 1;</code>
     */
    protected $timeStamp = '';
    /**
     *随机字符串
     *
     * Generated from protobuf field <code>string nonceStr = 2;</code>
     */
    protected $nonceStr = '';
    /**
     *订单详情扩展字符串
     *
     * Generated from protobuf field <code>string package = 3;</code>
     */
    protected $package = '';
    /**
     *签名方式
     *
     * Generated from protobuf field <code>string signType = 4;</code>
     */
    protected $signType = '';
    /**
     *签名
     *
     * Generated from protobuf field <code>string paySign = 5;</code>
     */
    protected $paySign = '';
    /**
     *app支付才有 商户号
     *
     * Generated from protobuf field <code>optional string partnerId = 6;</code>
     */
    protected $partnerId = null;
    /**
     *app支付才有 预支付交易会话ID
     *
     * Generated from protobuf field <code>optional string prepayId = 7;</code>
     */
    protected $prepayId = null;
    /**
     *二维码才有
     *
     * Generated from protobuf field <code>optional string mchId = 8;</code>
     */
    protected $mchId = null;
    /**
     *二维码才有
     *
     * Generated from protobuf field <code>optional string productId = 9;</code>
     */
    protected $productId = null;
    /**
     *wap返回参数
     *
     * Generated from protobuf field <code>optional string h5Url = 10;</code>
     */
    protected $h5Url = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $timeStamp
     *          因为微信的其奇怪设计，有两个时戳，一个小驼峰，一个不是。系统只返回一个，需要自行格式
     *     @type string $nonceStr
     *          随机字符串
     *     @type string $package
     *          订单详情扩展字符串
     *     @type string $signType
     *          签名方式
     *     @type string $paySign
     *          签名
     *     @type string $partnerId
     *          app支付才有 商户号
     *     @type string $prepayId
     *          app支付才有 预支付交易会话ID
     *     @type string $mchId
     *          二维码才有
     *     @type string $productId
     *          二维码才有
     *     @type string $h5Url
     *          wap返回参数
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     *因为微信的其奇怪设计，有两个时戳，一个小驼峰，一个不是。系统只返回一个，需要自行格式
     *
     * Generated from protobuf field <code>string timeStamp = 1;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->timeStamp;
    }

    /**
     *因为微信的其奇怪设计，有两个时戳，一个小驼峰，一个不是。系统只返回一个，需要自行格式
     *
     * Generated from protobuf field <code>string timeStamp = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->timeStamp = $var;

        return $this;
    }

    /**
     *随机字符串
     *
     * Generated from protobuf field <code>string nonceStr = 2;</code>
     * @return string
     */
    public function getNonceStr()
    {
        return $this->nonceStr;
    }

    /**
     *随机字符串
     *
     * Generated from protobuf field <code>string nonceStr = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNonceStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonceStr = $var;

        return $this;
    }

    /**
     *订单详情扩展字符串
     *
     * Generated from protobuf field <code>string package = 3;</code>
     * @return string
     */
    public function getPackage()
    {
        return $this->package;
    }

    /**
     *订单详情扩展字符串
     *
     * Generated from protobuf field <code>string package = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkString($var, True);
        $this->package = $var;

        return $this;
    }

    /**
     *签名方式
     *
     * Generated from protobuf field <code>string signType = 4;</code>
     * @return string
     */
    public function getSignType()
    {
        return $this->signType;
    }

    /**
     *签名方式
     *
     * Generated from protobuf field <code>string signType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignType($var)
    {
        GPBUtil::checkString($var, True);
        $this->signType = $var;

        return $this;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string paySign = 5;</code>
     * @return string
     */
    public function getPaySign()
    {
        return $this->paySign;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string paySign = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPaySign($var)
    {
        GPBUtil::checkString($var, True);
        $this->paySign = $var;

        return $this;
    }

    /**
     *app支付才有 商户号
     *
     * Generated from protobuf field <code>optional string partnerId = 6;</code>
     * @return string
     */
    public function getPartnerId()
    {
        return isset($this->partnerId) ? $this->partnerId : '';
    }

    public function hasPartnerId()
    {
        return isset($this->partnerId);
    }

    public function clearPartnerId()
    {
        unset($this->partnerId);
    }

    /**
     *app支付才有 商户号
     *
     * Generated from protobuf field <code>optional string partnerId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPartnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->partnerId = $var;

        return $this;
    }

    /**
     *app支付才有 预支付交易会话ID
     *
     * Generated from protobuf field <code>optional string prepayId = 7;</code>
     * @return string
     */
    public function getPrepayId()
    {
        return isset($this->prepayId) ? $this->prepayId : '';
    }

    public function hasPrepayId()
    {
        return isset($this->prepayId);
    }

    public function clearPrepayId()
    {
        unset($this->prepayId);
    }

    /**
     *app支付才有 预支付交易会话ID
     *
     * Generated from protobuf field <code>optional string prepayId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPrepayId($var)
    {
        GPBUtil::checkString($var, True);
        $this->prepayId = $var;

        return $this;
    }

    /**
     *二维码才有
     *
     * Generated from protobuf field <code>optional string mchId = 8;</code>
     * @return string
     */
    public function getMchId()
    {
        return isset($this->mchId) ? $this->mchId : '';
    }

    public function hasMchId()
    {
        return isset($this->mchId);
    }

    public function clearMchId()
    {
        unset($this->mchId);
    }

    /**
     *二维码才有
     *
     * Generated from protobuf field <code>optional string mchId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->mchId = $var;

        return $this;
    }

    /**
     *二维码才有
     *
     * Generated from protobuf field <code>optional string productId = 9;</code>
     * @return string
     */
    public function getProductId()
    {
        return isset($this->productId) ? $this->productId : '';
    }

    public function hasProductId()
    {
        return isset($this->productId);
    }

    public function clearProductId()
    {
        unset($this->productId);
    }

    /**
     *二维码才有
     *
     * Generated from protobuf field <code>optional string productId = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkString($var, True);
        $this->productId = $var;

        return $this;
    }

    /**
     *wap返回参数
     *
     * Generated from protobuf field <code>optional string h5Url = 10;</code>
     * @return string
     */
    public function getH5Url()
    {
        return isset($this->h5Url) ? $this->h5Url : '';
    }

    public function hasH5Url()
    {
        return isset($this->h5Url);
    }

    public function clearH5Url()
    {
        unset($this->h5Url);
    }

    /**
     *wap返回参数
     *
     * Generated from protobuf field <code>optional string h5Url = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setH5Url($var)
    {
        GPBUtil::checkString($var, True);
        $this->h5Url = $var;

        return $this;
    }

}

