<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *微信session
 *
 * Generated from protobuf message <code>proto.WxSessionResponse</code>
 */
class WxSessionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 会话密钥
     *
     * Generated from protobuf field <code>string sessionKey = 1;</code>
     */
    protected $sessionKey = '';
    /**
     * 用户唯一标识
     *
     * Generated from protobuf field <code>string openId = 2;</code>
     */
    protected $openId = '';
    /**
     * 用户在开放平台的唯一标识符
     *
     * Generated from protobuf field <code>string unionId = 3;</code>
     */
    protected $unionId = '';
    /**
     * 错误码
     *
     * Generated from protobuf field <code>int32 errCode = 4;</code>
     */
    protected $errCode = 0;
    /**
     * 错误信息
     *
     * Generated from protobuf field <code>string errMsg = 5;</code>
     */
    protected $errMsg = '';
    /**
     * 水印
     *
     * Generated from protobuf field <code>.proto.Watermark watermark = 6;</code>
     */
    protected $watermark = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sessionKey
     *           会话密钥
     *     @type string $openId
     *           用户唯一标识
     *     @type string $unionId
     *           用户在开放平台的唯一标识符
     *     @type int $errCode
     *           错误码
     *     @type string $errMsg
     *           错误信息
     *     @type \Proto\Watermark $watermark
     *           水印
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     * 会话密钥
     *
     * Generated from protobuf field <code>string sessionKey = 1;</code>
     * @return string
     */
    public function getSessionKey()
    {
        return $this->sessionKey;
    }

    /**
     * 会话密钥
     *
     * Generated from protobuf field <code>string sessionKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionKey = $var;

        return $this;
    }

    /**
     * 用户唯一标识
     *
     * Generated from protobuf field <code>string openId = 2;</code>
     * @return string
     */
    public function getOpenId()
    {
        return $this->openId;
    }

    /**
     * 用户唯一标识
     *
     * Generated from protobuf field <code>string openId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->openId = $var;

        return $this;
    }

    /**
     * 用户在开放平台的唯一标识符
     *
     * Generated from protobuf field <code>string unionId = 3;</code>
     * @return string
     */
    public function getUnionId()
    {
        return $this->unionId;
    }

    /**
     * 用户在开放平台的唯一标识符
     *
     * Generated from protobuf field <code>string unionId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->unionId = $var;

        return $this;
    }

    /**
     * 错误码
     *
     * Generated from protobuf field <code>int32 errCode = 4;</code>
     * @return int
     */
    public function getErrCode()
    {
        return $this->errCode;
    }

    /**
     * 错误码
     *
     * Generated from protobuf field <code>int32 errCode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setErrCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->errCode = $var;

        return $this;
    }

    /**
     * 错误信息
     *
     * Generated from protobuf field <code>string errMsg = 5;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->errMsg;
    }

    /**
     * 错误信息
     *
     * Generated from protobuf field <code>string errMsg = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->errMsg = $var;

        return $this;
    }

    /**
     * 水印
     *
     * Generated from protobuf field <code>.proto.Watermark watermark = 6;</code>
     * @return \Proto\Watermark|null
     */
    public function getWatermark()
    {
        return $this->watermark;
    }

    public function hasWatermark()
    {
        return isset($this->watermark);
    }

    public function clearWatermark()
    {
        unset($this->watermark);
    }

    /**
     * 水印
     *
     * Generated from protobuf field <code>.proto.Watermark watermark = 6;</code>
     * @param \Proto\Watermark $var
     * @return $this
     */
    public function setWatermark($var)
    {
        GPBUtil::checkMessage($var, \Proto\Watermark::class);
        $this->watermark = $var;

        return $this;
    }

}

