<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 微信发送订阅信息
 *
 * Generated from protobuf message <code>proto.WxSendTemplateMessageParam</code>
 */
class WxSendTemplateMessageParam extends \Google\Protobuf\Internal\Message
{
    /**
     *接收小程序appid
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     */
    protected $appId = '';
    /**
     *接收用户openid
     *
     * Generated from protobuf field <code>string toUser = 2;</code>
     */
    protected $toUser = '';
    /**
     *消息模版ID
     *
     * Generated from protobuf field <code>string templateId = 3;</code>
     */
    protected $templateId = '';
    /**
     *点击后的跳转页面，仅限本小程序内的页面
     *
     * Generated from protobuf field <code>string page = 4;</code>
     */
    protected $page = '';
    /**
     *模板内容
     *
     * Generated from protobuf field <code>string data = 5;</code>
     */
    protected $data = '';
    /**
     *跳转小程序类型：developer为开发版；trial为体验版；formal为正式版；默认为正式版
     *
     * Generated from protobuf field <code>string miniprogramState = 6;</code>
     */
    protected $miniprogramState = '';
    /**
     *进入小程序查看”的语言类型，支持zh_CN(简体中文)、en_US(英文)、zh_HK(繁体中文)、zh_TW(繁体中文)，默认为zh_CN
     *
     * Generated from protobuf field <code>string lang = 7;</code>
     */
    protected $lang = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appId
     *          接收小程序appid
     *     @type string $toUser
     *          接收用户openid
     *     @type string $templateId
     *          消息模版ID
     *     @type string $page
     *          点击后的跳转页面，仅限本小程序内的页面
     *     @type string $data
     *          模板内容
     *     @type string $miniprogramState
     *          跳转小程序类型：developer为开发版；trial为体验版；formal为正式版；默认为正式版
     *     @type string $lang
     *          进入小程序查看”的语言类型，支持zh_CN(简体中文)、en_US(英文)、zh_HK(繁体中文)、zh_TW(繁体中文)，默认为zh_CN
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat::initOnce();
        parent::__construct($data);
    }

    /**
     *接收小程序appid
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     *接收小程序appid
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

    /**
     *接收用户openid
     *
     * Generated from protobuf field <code>string toUser = 2;</code>
     * @return string
     */
    public function getToUser()
    {
        return $this->toUser;
    }

    /**
     *接收用户openid
     *
     * Generated from protobuf field <code>string toUser = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->toUser = $var;

        return $this;
    }

    /**
     *消息模版ID
     *
     * Generated from protobuf field <code>string templateId = 3;</code>
     * @return string
     */
    public function getTemplateId()
    {
        return $this->templateId;
    }

    /**
     *消息模版ID
     *
     * Generated from protobuf field <code>string templateId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->templateId = $var;

        return $this;
    }

    /**
     *点击后的跳转页面，仅限本小程序内的页面
     *
     * Generated from protobuf field <code>string page = 4;</code>
     * @return string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *点击后的跳转页面，仅限本小程序内的页面
     *
     * Generated from protobuf field <code>string page = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkString($var, True);
        $this->page = $var;

        return $this;
    }

    /**
     *模板内容
     *
     * Generated from protobuf field <code>string data = 5;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *模板内容
     *
     * Generated from protobuf field <code>string data = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     *跳转小程序类型：developer为开发版；trial为体验版；formal为正式版；默认为正式版
     *
     * Generated from protobuf field <code>string miniprogramState = 6;</code>
     * @return string
     */
    public function getMiniprogramState()
    {
        return $this->miniprogramState;
    }

    /**
     *跳转小程序类型：developer为开发版；trial为体验版；formal为正式版；默认为正式版
     *
     * Generated from protobuf field <code>string miniprogramState = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMiniprogramState($var)
    {
        GPBUtil::checkString($var, True);
        $this->miniprogramState = $var;

        return $this;
    }

    /**
     *进入小程序查看”的语言类型，支持zh_CN(简体中文)、en_US(英文)、zh_HK(繁体中文)、zh_TW(繁体中文)，默认为zh_CN
     *
     * Generated from protobuf field <code>string lang = 7;</code>
     * @return string
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     *进入小程序查看”的语言类型，支持zh_CN(简体中文)、en_US(英文)、zh_HK(繁体中文)、zh_TW(繁体中文)，默认为zh_CN
     *
     * Generated from protobuf field <code>string lang = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;

        return $this;
    }

}

