<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/addr.proto

namespace GPBMetadata\Proto;

class Addr
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ù
proto/addr.protoproto"
AddressParam
address (	"§
ExpressExtractResponse
	houseInfo (	
poiInfo (	
town (	
city (	
district (	
tel (	
addrInfo (	
per (	
prov	 (	"+
CompleteAddressResponse
complete (	BZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

