<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/alipush.proto

namespace GPBMetadata\Proto;

class Alipush
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
proto/alipush.protoproto"ƒ
AliPushParam

deviceType (	
client (	
title (	
body (	
pushType (	
extParameters (	
target (	
targetValue (	
pushTime	 (

expireTime
 (
iOSModel (	
androidBarType (
storeOffline ("7
AliPushResponse
	messageId (	
	requestId (	BZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

