<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/base.proto

namespace GPBMetadata\Proto;

class Base
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
¹
proto/base.protoproto"M
BaseResponse
code (
msg (	"
data (2.google.protobuf.Any"+
	PageParam
page (
pageSize ("

NoReturn"
EmptyBZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

