<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dypns.proto

namespace GPBMetadata\Proto;

class Dypns
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
{
proto/dypns.protoproto"(
AliGetMobileParam
accessToken (	"&
AliGetMobileResponse
mobile (	BZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

