<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dyvms.proto

namespace GPBMetadata\Proto;

class Dyvms
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
š
proto/dyvms.protoproto"i
CallTTSParam
phone (	
ttsCode (	&
ttsParam (2.google.protobuf.Any
	playTimes ("2
CallVoiceParam
phone (	
	voiceCode (	"P
CallResponse
	requestId (	
message (	
callId (	
code (	BZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

