<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/jpush.proto

namespace GPBMetadata\Proto;

class Jpush
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
Â
proto/jpush.protoproto"g
JPushAliasParam
content (	
sound (	
alias (	%
extinfo (2.google.protobuf.Any".
JPushResponse
sendno (	
msgId (	BZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

