<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/nls.proto

namespace GPBMetadata\Proto;

class Nls
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ƒ
proto/nls.protoproto"Z
RecognizeSpeechResponse
message (	
result (	
status (
taskId (	BZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

