<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

namespace GPBMetadata\Proto;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Base::initOnce();
        \GPBMetadata\Proto\Pay::initOnce();
        \GPBMetadata\Proto\Sms::initOnce();
        \GPBMetadata\Proto\Oss::initOnce();
        \GPBMetadata\Proto\Addr::initOnce();
        \GPBMetadata\Proto\Dypns::initOnce();
        \GPBMetadata\Proto\Dyvms::initOnce();
        \GPBMetadata\Proto\Goodstech::initOnce();
        \GPBMetadata\Proto\Nls::initOnce();
        \GPBMetadata\Proto\Upload::initOnce();
        \GPBMetadata\Proto\Ocr::initOnce();
        \GPBMetadata\Proto\Alipush::initOnce();
        \GPBMetadata\Proto\Amap::initOnce();
        \GPBMetadata\Proto\Mqtt::initOnce();
        \GPBMetadata\Proto\Wechat::initOnce();
        $pool->internalAddGeneratedFile(
            '
™
proto/service.protoprotoproto/pay.protoproto/sms.protoproto/oss.protoproto/addr.protoproto/dypns.protoproto/dyvms.protoproto/goodstech.protoproto/nls.protoproto/upload.protoproto/ocr.protoproto/alipush.protoproto/amap.protoproto/mqtt.protoproto/wechat.proto2ë
BaseA
RpcSendAuthSms.proto.SendAuthSmsParam.proto.SendSmsResponseK
RpcVerifyAuthSms.proto.VerifyAuthSmsParam.proto.VerifyAuthSmsResponse9

RpcSendSms.proto.SendSmsParam.proto.SendSmsResponseN
RpcGetPolicyToken.proto.OSSPolicyTokenParam.proto.OSSPolicyTokenResponseH
RpcOssUploadByte.proto.OSSUploadByteParam.proto.OSSFileUrlResponseG
RpcExpressExtract.proto.AddressParam.proto.ExpressExtractResponseI
RpcCompleteAddress.proto.AddressParam.proto.CompleteAddressResponseH
RpcAliGetMobile.proto.AliGetMobileParam.proto.AliGetMobileResponse6

RpcCallTTS.proto.CallTTSParam.proto.CallResponse:
RpcCallVoice.proto.CallVoiceParam.proto.CallResponseD
RpcAliGoodstech.proto.GoodsTenchParam.proto.GoodsTenchResponseI
RpcSpeechRecognizer.proto.UploadParam.proto.RecognizeSpeechResponsem
RpcBusinessLicenseRecognizer$.proto.RecognizeBusinessLicenseParam\'.proto.RecognizeBusinessLicenseResponsed
RpcIdentityCardRecognizer!.proto.RecognizeIdentityCardParam$.proto.RecognizeIdentityCardResponse9

RpcAliPush.proto.AliPushParam.proto.AliPushResponse?
RpcAmapCycling.proto.AmapLocationParam.proto.AmapResponse6

RpcAmapGeo.proto.AmapGeoParam.proto.AmapResponse:
RpcAmapRegeo.proto.AmapRegeoParam.proto.AmapResponse@
RpcAmapDistance.proto.AmapDistanceParam.proto.AmapResponseD
RpcMqttPrintOrder.proto.MqttPrintOrderParam.proto.BaseResponseA
RpcMqttNotice.proto.MqttVoiceNoticeParam.proto.BaseResponseM
RpcMqttClientList.proto.MqttQueryClinetsParam.proto.MqttClientsResponseI
RpcCreateMiniSceneCode.proto.WxMiniCodeParam.proto.MiniCodeResponseK
RpcCreateMiniDefaultCode.proto.WxMiniPathParam.proto.MiniCodeResponseC
RpcWxCodeGetSession.proto.WxUserParam.proto.WxSessionResponseE
RpcWxOpenIdGetUserInfo.proto.WxUserParam.proto.WxPublicUserInfoJ
RpcWxDecryptPhoneInfo.proto.WxUserParam.proto.WxDecryptPhoneResponseL
RpcWxDecryptUserInfo.proto.WxUserParam .proto.WxDecryptUserInfoResponse2y
Pay0
RpcPayOrder.proto.PayParam.proto.PayReturn@
RpcQueryOrder.proto.QueryOrderParam.proto.QueryOrderRetrunBZ/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

